table hha
	lineageTag: f4cf0e81-ca62-45f8-9400-25c4d7d8e835

	column BENE_ID
		dataType: int64
		formatString: 0
		lineageTag: af7a03b3-285a-4718-9035-eeeba09952f8
		summarizeBy: count
		sourceColumn: BENE_ID

		annotation SummarizationSetBy = Automatic

	column CLM_ID
		dataType: int64
		formatString: 0
		lineageTag: 5ee6fc16-f95a-40ce-bf77-37cadc256ab9
		summarizeBy: count
		sourceColumn: CLM_ID

		annotation SummarizationSetBy = Automatic

	column NCH_NEAR_LINE_REC_IDENT_CD
		dataType: string
		lineageTag: 11ce916b-1739-4c66-88ba-fef7bb9c6d7f
		summarizeBy: none
		sourceColumn: NCH_NEAR_LINE_REC_IDENT_CD

		annotation SummarizationSetBy = Automatic

	column NCH_CLM_TYPE_CD
		dataType: int64
		formatString: 0
		lineageTag: 2bd070f1-5fe1-4215-9814-66bdb03734e2
		summarizeBy: sum
		sourceColumn: NCH_CLM_TYPE_CD

		annotation SummarizationSetBy = Automatic

	column CLM_FROM_DT
		dataType: dateTime
		formatString: Short Date
		lineageTag: 9699c89d-b15f-450b-9077-0f5c0db6435f
		summarizeBy: none
		sourceColumn: CLM_FROM_DT

		variation Variation
			isDefault
			relationship: 78517829-2900-4d8b-a20d-440d422fba5c
			defaultHierarchy: LocalDateTable_e5918c10-9965-4096-af07-541fbe561649.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CLM_THRU_DT
		dataType: dateTime
		formatString: Short Date
		lineageTag: c6a311de-9b2c-40e2-9fe6-fbc95bd01e53
		summarizeBy: none
		sourceColumn: CLM_THRU_DT

		variation Variation
			isDefault
			relationship: 13037cac-74ee-43ff-9510-5736e0cdd8f8
			defaultHierarchy: LocalDateTable_15b790bc-ade2-4ab1-85a0-ac695241556d.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column NCH_WKLY_PROC_DT
		dataType: dateTime
		formatString: Long Date
		lineageTag: f3312ff7-9101-4c94-8d40-7d0b911c5f75
		summarizeBy: none
		sourceColumn: NCH_WKLY_PROC_DT

		variation Variation
			isDefault
			relationship: 4d7fb7ee-1ab2-4178-b43e-19cabc25b4bb
			defaultHierarchy: LocalDateTable_b4f1ea2b-00a2-43ff-8221-2288187f8a2c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column FI_CLM_PROC_DT
		dataType: string
		lineageTag: 514e4a04-6f0b-4c36-aecd-7ab1b9e53d79
		summarizeBy: none
		sourceColumn: FI_CLM_PROC_DT

		annotation SummarizationSetBy = Automatic

	column PRVDR_NUM
		dataType: string
		lineageTag: 3ef96029-1b18-4054-807f-efa435984c43
		summarizeBy: none
		sourceColumn: PRVDR_NUM

		annotation SummarizationSetBy = Automatic

	column CLM_FAC_TYPE_CD
		dataType: int64
		formatString: 0
		lineageTag: e259bfc9-2b90-4893-8e79-4f987656fe11
		summarizeBy: sum
		sourceColumn: CLM_FAC_TYPE_CD

		annotation SummarizationSetBy = Automatic

	column CLM_SRVC_CLSFCTN_TYPE_CD
		dataType: int64
		formatString: 0
		lineageTag: afd508b7-ea42-4d57-9624-336363beadff
		summarizeBy: sum
		sourceColumn: CLM_SRVC_CLSFCTN_TYPE_CD

		annotation SummarizationSetBy = Automatic

	column CLM_FREQ_CD
		dataType: int64
		formatString: 0
		lineageTag: 4b100a1b-c19a-416d-9103-0aa87cabc48f
		summarizeBy: sum
		sourceColumn: CLM_FREQ_CD

		annotation SummarizationSetBy = Automatic

	column FI_NUM
		dataType: string
		lineageTag: 3ad59c23-29e3-4de1-8a5c-aaf8ff8e15d2
		summarizeBy: none
		sourceColumn: FI_NUM

		annotation SummarizationSetBy = Automatic

	column CLM_MDCR_NON_PMT_RSN_CD
		dataType: string
		lineageTag: 9bbf4f12-9ef5-436c-b101-c3756ec3c240
		summarizeBy: none
		sourceColumn: CLM_MDCR_NON_PMT_RSN_CD

		annotation SummarizationSetBy = Automatic

	column CLM_PMT_AMT
		dataType: double
		lineageTag: c65b4147-09be-47e6-b6f0-7cb515e29eb2
		summarizeBy: sum
		sourceColumn: CLM_PMT_AMT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NCH_PRMRY_PYR_CLM_PD_AMT
		dataType: double
		lineageTag: 272febdd-ce45-4bb2-be98-0354d4cd6d60
		summarizeBy: sum
		sourceColumn: NCH_PRMRY_PYR_CLM_PD_AMT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NCH_PRMRY_PYR_CD
		dataType: string
		lineageTag: 6fbb5d0a-ce32-402c-b13d-670710d2535a
		summarizeBy: none
		sourceColumn: NCH_PRMRY_PYR_CD

		annotation SummarizationSetBy = Automatic

	column PRVDR_STATE_CD
		dataType: int64
		formatString: 0
		lineageTag: 89111848-a58d-4b68-8926-c6a3e7608e75
		summarizeBy: sum
		sourceColumn: PRVDR_STATE_CD

		annotation SummarizationSetBy = Automatic

	column ORG_NPI_NUM
		dataType: int64
		formatString: 0
		lineageTag: ba80f032-c559-488a-80ad-8d8f645941f7
		summarizeBy: sum
		sourceColumn: ORG_NPI_NUM

		annotation SummarizationSetBy = Automatic

	column AT_PHYSN_UPIN
		dataType: string
		lineageTag: 12d2e4d8-3d11-47b7-b10a-629f65db691c
		summarizeBy: none
		sourceColumn: AT_PHYSN_UPIN

		annotation SummarizationSetBy = Automatic

	column AT_PHYSN_NPI
		dataType: int64
		formatString: 0
		lineageTag: 890ac2ae-c9f6-4d48-b6dd-52242adb1f0c
		summarizeBy: sum
		sourceColumn: AT_PHYSN_NPI

		annotation SummarizationSetBy = Automatic

	column PTNT_DSCHRG_STUS_CD
		dataType: int64
		formatString: 0
		lineageTag: 5e7c120c-fda1-4df6-8933-24669017d4e7
		summarizeBy: sum
		sourceColumn: PTNT_DSCHRG_STUS_CD

		annotation SummarizationSetBy = Automatic

	column CLM_PPS_IND_CD
		dataType: string
		lineageTag: c5fb409b-b9bb-476d-bd9c-774e37ca2c4f
		summarizeBy: none
		sourceColumn: CLM_PPS_IND_CD

		annotation SummarizationSetBy = Automatic

	column CLM_TOT_CHRG_AMT
		dataType: double
		lineageTag: de781bab-6a38-4ecb-96e0-8c5420d46cfa
		summarizeBy: sum
		sourceColumn: CLM_TOT_CHRG_AMT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PRNCPAL_DGNS_CD
		dataType: string
		lineageTag: f771b0c6-44fb-40ed-9cd9-b612aa336e62
		summarizeBy: none
		sourceColumn: PRNCPAL_DGNS_CD

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD1
		dataType: string
		lineageTag: 0c6a9285-93a2-4157-bcd7-77b8b3d6aee5
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD1

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD2
		dataType: string
		lineageTag: 18ca80c3-4029-4412-b9d1-5c9b2675b796
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD2

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD3
		dataType: string
		lineageTag: 950136bf-d87a-4eea-8c0b-b7e4bdfe4679
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD3

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD4
		dataType: string
		lineageTag: a61fa7d9-2a17-4415-9eaa-d3f7425120b8
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD4

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD5
		dataType: string
		lineageTag: 4899d1fe-49d8-4549-b004-564c5ceb84c5
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD5

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD6
		dataType: string
		lineageTag: 426d0e38-1935-4f49-823b-2fa7c40896f0
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD6

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD7
		dataType: string
		lineageTag: 6b83831f-babd-470e-b280-db425e1ab944
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD7

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD8
		dataType: string
		lineageTag: b9de48ca-97d7-4fba-a485-90cb79d3b0f1
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD8

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD9
		dataType: string
		lineageTag: 57390a4c-c39f-4ce4-8612-948af6944ebb
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD9

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD10
		dataType: string
		lineageTag: 475ca098-36df-4d7d-a04d-8fabf7340d91
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD10

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD11
		dataType: string
		lineageTag: 854c147b-b041-4cce-894d-f3115e08aa19
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD11

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD12
		dataType: string
		lineageTag: 0cdd1ffa-73cc-4286-9ebe-b88ce0c635c4
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD12

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD13
		dataType: string
		lineageTag: 7592229d-e185-4fa8-8d9d-2651d509434e
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD13

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD14
		dataType: string
		lineageTag: 139ebfbf-d96d-45da-826d-21b53e88cbc1
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD14

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD15
		dataType: string
		lineageTag: 614ed745-3330-488a-be51-93c96e1c8e71
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD15

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD16
		dataType: string
		lineageTag: 3eb9d9cf-b986-44d0-930f-9c160b3940dd
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD16

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD17
		dataType: string
		lineageTag: 4f9fe27a-e0ff-49b5-9a9a-12ba9cd34104
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD17

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD18
		dataType: string
		lineageTag: 0735fc70-25b4-4dbb-96b4-a49968b4cda8
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD18

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD19
		dataType: string
		lineageTag: 0ed28959-0a2d-4027-b3d1-f27bcc08b676
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD19

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD20
		dataType: string
		lineageTag: e7741795-2cd0-4597-ae1f-adecf1954bd0
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD20

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD21
		dataType: string
		lineageTag: 2d0d0e32-0b16-48a8-a165-9b92c7277673
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD21

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD22
		dataType: string
		lineageTag: a438b151-2925-4271-9116-3d5a740916cc
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD22

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD23
		dataType: string
		lineageTag: 2ff24e28-4a74-4de0-861b-10e2d7a06fdc
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD23

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD24
		dataType: string
		lineageTag: b37c9579-e4fe-4c50-b21e-644b7d7831b1
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD24

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD25
		dataType: string
		lineageTag: 64a3920d-586d-4eef-a11a-a457ace6dafc
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD25

		annotation SummarizationSetBy = Automatic

	column FST_DGNS_E_CD
		dataType: string
		lineageTag: 4104b9aa-bacb-4aac-8b42-bebfbd6496ca
		summarizeBy: none
		sourceColumn: FST_DGNS_E_CD

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_E_CD1
		dataType: string
		lineageTag: fdf95927-bbe1-449c-b1d8-46e34cc0389e
		summarizeBy: none
		sourceColumn: ICD_DGNS_E_CD1

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_E_CD2
		dataType: string
		lineageTag: 3f88e8b6-c300-4a5b-99e5-9ccbd142efb9
		summarizeBy: none
		sourceColumn: ICD_DGNS_E_CD2

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_E_CD3
		dataType: string
		lineageTag: f497384b-94b3-41c4-b5f2-0b53814438d9
		summarizeBy: none
		sourceColumn: ICD_DGNS_E_CD3

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_E_CD4
		dataType: string
		lineageTag: e40fd51a-dc47-46c5-95a5-a72382ee5c05
		summarizeBy: none
		sourceColumn: ICD_DGNS_E_CD4

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_E_CD5
		dataType: string
		lineageTag: 33e35f69-dd29-4e1f-9aee-d940286d749d
		summarizeBy: none
		sourceColumn: ICD_DGNS_E_CD5

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_E_CD6
		dataType: string
		lineageTag: 04b03c87-e6d6-44fc-b155-19c10b214808
		summarizeBy: none
		sourceColumn: ICD_DGNS_E_CD6

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_E_CD7
		dataType: string
		lineageTag: 707a6494-3a9c-4719-9ff9-7f6cd5fc8618
		summarizeBy: none
		sourceColumn: ICD_DGNS_E_CD7

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_E_CD8
		dataType: string
		lineageTag: 90a23ee8-fb69-49f1-ac5c-9ee425369ab9
		summarizeBy: none
		sourceColumn: ICD_DGNS_E_CD8

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_E_CD9
		dataType: string
		lineageTag: 59bda975-c604-424b-a277-39cd2c6737e1
		summarizeBy: none
		sourceColumn: ICD_DGNS_E_CD9

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_E_CD10
		dataType: string
		lineageTag: da18f06c-8ece-452a-8d0a-e7e3ab69dc30
		summarizeBy: none
		sourceColumn: ICD_DGNS_E_CD10

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_E_CD11
		dataType: string
		lineageTag: 3ca757a0-c2e7-4c20-8c31-d0fafcf92965
		summarizeBy: none
		sourceColumn: ICD_DGNS_E_CD11

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_E_CD12
		dataType: string
		lineageTag: 887c4a13-2be4-4650-943f-333ce2d0fa2e
		summarizeBy: none
		sourceColumn: ICD_DGNS_E_CD12

		annotation SummarizationSetBy = Automatic

	column CLM_HHA_LUPA_IND_CD
		dataType: string
		lineageTag: a4e23e87-6a2f-42ec-b39d-92e2e50702eb
		summarizeBy: none
		sourceColumn: CLM_HHA_LUPA_IND_CD

		annotation SummarizationSetBy = Automatic

	column CLM_HHA_RFRL_CD
		dataType: string
		lineageTag: 920d4ec5-133b-4276-967b-9c98d18f30c6
		summarizeBy: none
		sourceColumn: CLM_HHA_RFRL_CD

		annotation SummarizationSetBy = Automatic

	column CLM_HHA_TOT_VISIT_CNT
		dataType: int64
		formatString: 0
		lineageTag: 64d10f1d-c875-4cd5-bf60-887d71ea3c50
		summarizeBy: sum
		sourceColumn: CLM_HHA_TOT_VISIT_CNT

		annotation SummarizationSetBy = Automatic

	column CLM_ADMSN_DT
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4b383f86-f4d2-4583-a959-c196f02ca4c0
		summarizeBy: none
		sourceColumn: CLM_ADMSN_DT

		variation Variation
			isDefault
			relationship: 61460481-042e-4cce-b0a3-1f109a661d7c
			defaultHierarchy: LocalDateTable_72f321bf-7b66-4d58-a9dc-5bc2e56006b2.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CLAIM_QUERY_CODE
		dataType: int64
		formatString: 0
		lineageTag: 7bd42f1f-bd17-45b2-b202-b318ae3d2be1
		summarizeBy: sum
		sourceColumn: CLAIM_QUERY_CODE

		annotation SummarizationSetBy = Automatic

	column CLM_LINE_NUM
		dataType: int64
		formatString: 0
		lineageTag: 0cf289fd-f57d-4eeb-bd1d-fc8bae1ffe56
		summarizeBy: sum
		sourceColumn: CLM_LINE_NUM

		annotation SummarizationSetBy = Automatic

	column REV_CNTR
		dataType: int64
		formatString: 0
		lineageTag: 4998c437-e15b-4eb4-8c78-4a23d9781933
		summarizeBy: sum
		sourceColumn: REV_CNTR

		annotation SummarizationSetBy = Automatic

	column REV_CNTR_DT
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4d94d404-2f6d-4140-9944-40f42a36947a
		summarizeBy: none
		sourceColumn: REV_CNTR_DT

		variation Variation
			isDefault
			relationship: 388234bd-2461-4bb7-ac37-a9f2fb22470f
			defaultHierarchy: LocalDateTable_744f473c-a361-4e1e-91a5-76693ebc7c13.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column REV_CNTR_1ST_ANSI_CD
		dataType: string
		lineageTag: 5ab846b2-e9f8-4be1-82c5-e68445a5cdb7
		summarizeBy: none
		sourceColumn: REV_CNTR_1ST_ANSI_CD

		annotation SummarizationSetBy = Automatic

	column REV_CNTR_APC_HIPPS_CD
		dataType: string
		lineageTag: 22dec589-2cb5-44e1-ae1a-d21ade0fdd43
		summarizeBy: none
		sourceColumn: REV_CNTR_APC_HIPPS_CD

		annotation SummarizationSetBy = Automatic

	column HCPCS_CD
		dataType: string
		lineageTag: 8d5e171d-1c45-435f-a14d-6972b8834334
		summarizeBy: none
		sourceColumn: HCPCS_CD

		annotation SummarizationSetBy = Automatic

	column HCPCS_1ST_MDFR_CD
		dataType: string
		lineageTag: a0421e04-349d-4237-b295-9ed1e2bf34bb
		summarizeBy: none
		sourceColumn: HCPCS_1ST_MDFR_CD

		annotation SummarizationSetBy = Automatic

	column HCPCS_2ND_MDFR_CD
		dataType: string
		lineageTag: d7ee0195-a9c6-4aa6-8b79-3ea6ce76cf38
		summarizeBy: none
		sourceColumn: HCPCS_2ND_MDFR_CD

		annotation SummarizationSetBy = Automatic

	column REV_CNTR_PMT_MTHD_IND_CD
		dataType: int64
		formatString: 0
		lineageTag: d239399c-616f-4ab8-ad35-328ade4105fe
		summarizeBy: sum
		sourceColumn: REV_CNTR_PMT_MTHD_IND_CD

		annotation SummarizationSetBy = Automatic

	column REV_CNTR_UNIT_CNT
		dataType: int64
		formatString: 0
		lineageTag: 9665c4df-6441-45f7-a332-111e68f53495
		summarizeBy: sum
		sourceColumn: REV_CNTR_UNIT_CNT

		annotation SummarizationSetBy = Automatic

	column REV_CNTR_RATE_AMT
		dataType: double
		lineageTag: 4f2f0c28-b5d0-4d1c-858d-fbe4e872c3b6
		summarizeBy: sum
		sourceColumn: REV_CNTR_RATE_AMT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column REV_CNTR_PMT_AMT_AMT
		dataType: double
		lineageTag: f2ed291e-b93c-4652-b842-b4b525db371c
		summarizeBy: sum
		sourceColumn: REV_CNTR_PMT_AMT_AMT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column REV_CNTR_TOT_CHRG_AMT
		dataType: double
		lineageTag: 403e111f-3ce3-444d-98f5-d04a4d881179
		summarizeBy: sum
		sourceColumn: REV_CNTR_TOT_CHRG_AMT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column REV_CNTR_NCVRD_CHRG_AMT
		dataType: double
		lineageTag: 06782c99-43a8-4565-90b4-4304aa83dd26
		summarizeBy: sum
		sourceColumn: REV_CNTR_NCVRD_CHRG_AMT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column REV_CNTR_DDCTBL_COINSRNC_CD
		dataType: int64
		formatString: 0
		lineageTag: e29f0947-425e-46a0-bc6e-53df6695fde9
		summarizeBy: sum
		sourceColumn: REV_CNTR_DDCTBL_COINSRNC_CD

		annotation SummarizationSetBy = Automatic

	column REV_CNTR_STUS_IND_CD
		dataType: int64
		formatString: 0
		lineageTag: 82b1f78b-a58f-43d1-ab17-879da15121c9
		summarizeBy: sum
		sourceColumn: REV_CNTR_STUS_IND_CD

		annotation SummarizationSetBy = Automatic

	column REV_CNTR_NDC_QTY
		dataType: string
		lineageTag: 5e13a3b8-75b0-4501-bf0c-4ab9ebfcb14b
		summarizeBy: none
		sourceColumn: REV_CNTR_NDC_QTY

		annotation SummarizationSetBy = Automatic

	column REV_CNTR_NDC_QTY_QLFR_CD
		dataType: string
		lineageTag: 8cb23613-4f20-4ca6-8ac3-1a3be43cc2bc
		summarizeBy: none
		sourceColumn: REV_CNTR_NDC_QTY_QLFR_CD

		annotation SummarizationSetBy = Automatic

	column RNDRNG_PHYSN_UPIN
		dataType: string
		lineageTag: 55a559db-fd8d-4d84-bdaa-afba8602b980
		summarizeBy: none
		sourceColumn: RNDRNG_PHYSN_UPIN

		annotation SummarizationSetBy = Automatic

	column RNDRNG_PHYSN_NPI
		dataType: int64
		formatString: 0
		lineageTag: f6dbab6f-46cb-4d0b-9765-33cb7db7e2e7
		summarizeBy: sum
		sourceColumn: RNDRNG_PHYSN_NPI

		annotation SummarizationSetBy = Automatic

	partition hha = m
		mode: import
		source =
				let
				    Source = Folder.Files("C:\Users\dpnsh\Downloads\All FFS Claims"),
				    #"C:\Users\dpnsh\Downloads\All FFS Claims\_hha csv1" = Source{[#"Folder Path"="C:\Users\dpnsh\Downloads\All FFS Claims\",Name="hha.csv"]}[Content],
				    #"Imported CSV" = Csv.Document(#"C:\Users\dpnsh\Downloads\All FFS Claims\_hha csv1",[Delimiter="|", Columns=88, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Imported CSV", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"BENE_ID", Int64.Type}, {"CLM_ID", Int64.Type}, {"NCH_NEAR_LINE_REC_IDENT_CD", type text}, {"NCH_CLM_TYPE_CD", Int64.Type}, {"CLM_FROM_DT", type date}, {"CLM_THRU_DT", type date}, {"NCH_WKLY_PROC_DT", type date}, {"FI_CLM_PROC_DT", type text}, {"PRVDR_NUM", type text}, {"CLM_FAC_TYPE_CD", Int64.Type}, {"CLM_SRVC_CLSFCTN_TYPE_CD", Int64.Type}, {"CLM_FREQ_CD", Int64.Type}, {"FI_NUM", type text}, {"CLM_MDCR_NON_PMT_RSN_CD", type text}, {"CLM_PMT_AMT", type number}, {"NCH_PRMRY_PYR_CLM_PD_AMT", type number}, {"NCH_PRMRY_PYR_CD", type text}, {"PRVDR_STATE_CD", Int64.Type}, {"ORG_NPI_NUM", Int64.Type}, {"AT_PHYSN_UPIN", type text}, {"AT_PHYSN_NPI", Int64.Type}, {"PTNT_DSCHRG_STUS_CD", Int64.Type}, {"CLM_PPS_IND_CD", type text}, {"CLM_TOT_CHRG_AMT", type number}, {"PRNCPAL_DGNS_CD", type text}, {"ICD_DGNS_CD1", type text}, {"ICD_DGNS_CD2", type text}, {"ICD_DGNS_CD3", type text}, {"ICD_DGNS_CD4", type text}, {"ICD_DGNS_CD5", type text}, {"ICD_DGNS_CD6", type text}, {"ICD_DGNS_CD7", type text}, {"ICD_DGNS_CD8", type text}, {"ICD_DGNS_CD9", type text}, {"ICD_DGNS_CD10", type text}, {"ICD_DGNS_CD11", type text}, {"ICD_DGNS_CD12", type text}, {"ICD_DGNS_CD13", type text}, {"ICD_DGNS_CD14", type text}, {"ICD_DGNS_CD15", type text}, {"ICD_DGNS_CD16", type text}, {"ICD_DGNS_CD17", type text}, {"ICD_DGNS_CD18", type text}, {"ICD_DGNS_CD19", type text}, {"ICD_DGNS_CD20", type text}, {"ICD_DGNS_CD21", type text}, {"ICD_DGNS_CD22", type text}, {"ICD_DGNS_CD23", type text}, {"ICD_DGNS_CD24", type text}, {"ICD_DGNS_CD25", type text}, {"FST_DGNS_E_CD", type text}, {"ICD_DGNS_E_CD1", type text}, {"ICD_DGNS_E_CD2", type text}, {"ICD_DGNS_E_CD3", type text}, {"ICD_DGNS_E_CD4", type text}, {"ICD_DGNS_E_CD5", type text}, {"ICD_DGNS_E_CD6", type text}, {"ICD_DGNS_E_CD7", type text}, {"ICD_DGNS_E_CD8", type text}, {"ICD_DGNS_E_CD9", type text}, {"ICD_DGNS_E_CD10", type text}, {"ICD_DGNS_E_CD11", type text}, {"ICD_DGNS_E_CD12", type text}, {"CLM_HHA_LUPA_IND_CD", type text}, {"CLM_HHA_RFRL_CD", type text}, {"CLM_HHA_TOT_VISIT_CNT", Int64.Type}, {"CLM_ADMSN_DT", type date}, {"CLAIM_QUERY_CODE", Int64.Type}, {"CLM_LINE_NUM", Int64.Type}, {"REV_CNTR", Int64.Type}, {"REV_CNTR_DT", type date}, {"REV_CNTR_1ST_ANSI_CD", type text}, {"REV_CNTR_APC_HIPPS_CD", type text}, {"HCPCS_CD", type text}, {"HCPCS_1ST_MDFR_CD", type text}, {"HCPCS_2ND_MDFR_CD", type text}, {"REV_CNTR_PMT_MTHD_IND_CD", Int64.Type}, {"REV_CNTR_UNIT_CNT", Int64.Type}, {"REV_CNTR_RATE_AMT", type number}, {"REV_CNTR_PMT_AMT_AMT", type number}, {"REV_CNTR_TOT_CHRG_AMT", type number}, {"REV_CNTR_NCVRD_CHRG_AMT", type number}, {"REV_CNTR_DDCTBL_COINSRNC_CD", Int64.Type}, {"REV_CNTR_STUS_IND_CD", Int64.Type}, {"REV_CNTR_NDC_QTY", type text}, {"REV_CNTR_NDC_QTY_QLFR_CD", type text}, {"RNDRNG_PHYSN_UPIN", type text}, {"RNDRNG_PHYSN_NPI", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

