table hospice
	lineageTag: b9dc9e87-6436-447a-ba2a-a3bce7d15099

	column BENE_ID
		dataType: int64
		formatString: 0
		lineageTag: d882f80f-0d57-4313-9241-b1d02f7480bb
		summarizeBy: count
		sourceColumn: BENE_ID

		annotation SummarizationSetBy = Automatic

	column CLM_ID
		dataType: int64
		formatString: 0
		lineageTag: 8e4a1dfa-0efa-4416-bcfa-42daaacd8438
		summarizeBy: count
		sourceColumn: CLM_ID

		annotation SummarizationSetBy = Automatic

	column NCH_NEAR_LINE_REC_IDENT_CD
		dataType: string
		lineageTag: 0c84748c-6ca7-42f9-bc9d-6cb47ee49efc
		summarizeBy: none
		sourceColumn: NCH_NEAR_LINE_REC_IDENT_CD

		annotation SummarizationSetBy = Automatic

	column NCH_CLM_TYPE_CD
		dataType: int64
		formatString: 0
		lineageTag: 50e4665c-11f8-4997-9627-006b8a7f7da8
		summarizeBy: sum
		sourceColumn: NCH_CLM_TYPE_CD

		annotation SummarizationSetBy = Automatic

	column CLM_FROM_DT
		dataType: dateTime
		formatString: Short Date
		lineageTag: 2190c642-feba-49a2-9fbd-5d45746bfb92
		summarizeBy: none
		sourceColumn: CLM_FROM_DT

		variation Variation
			isDefault
			relationship: 43385645-232d-40aa-a2c6-6996f04ff88a
			defaultHierarchy: LocalDateTable_0d76e566-3a5c-4c0f-9c1a-1bf942d9b136.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CLM_THRU_DT
		dataType: dateTime
		formatString: Short Date
		lineageTag: a7de3151-2122-4d5c-82ce-a9ef1510858e
		summarizeBy: none
		sourceColumn: CLM_THRU_DT

		variation Variation
			isDefault
			relationship: 14b0d925-4ff7-4e9d-8e2b-49a4ffbe12c2
			defaultHierarchy: LocalDateTable_5bd205e6-4dd7-4da0-af11-beced0ce6d35.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column NCH_WKLY_PROC_DT
		dataType: dateTime
		formatString: Long Date
		lineageTag: 29009d4a-d7fd-47f6-835d-907c0743245d
		summarizeBy: none
		sourceColumn: NCH_WKLY_PROC_DT

		variation Variation
			isDefault
			relationship: 55aacf7e-666f-42ed-80de-94df8e73a926
			defaultHierarchy: LocalDateTable_88f41b7b-01cc-4fd9-b998-ec37a2d8a908.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column FI_CLM_PROC_DT
		dataType: string
		lineageTag: 43b3b82b-a6c9-400c-83d7-ec5c78c35643
		summarizeBy: none
		sourceColumn: FI_CLM_PROC_DT

		annotation SummarizationSetBy = Automatic

	column PRVDR_NUM
		dataType: string
		lineageTag: 5a2202fa-1e16-4702-b91f-9318f7dd0aec
		summarizeBy: none
		sourceColumn: PRVDR_NUM

		annotation SummarizationSetBy = Automatic

	column CLM_FAC_TYPE_CD
		dataType: int64
		formatString: 0
		lineageTag: 977542f6-53e5-4f0b-90b7-159f8acd75c0
		summarizeBy: sum
		sourceColumn: CLM_FAC_TYPE_CD

		annotation SummarizationSetBy = Automatic

	column CLM_SRVC_CLSFCTN_TYPE_CD
		dataType: int64
		formatString: 0
		lineageTag: 1c41d269-569b-44fc-9a04-37b676b4d56f
		summarizeBy: sum
		sourceColumn: CLM_SRVC_CLSFCTN_TYPE_CD

		annotation SummarizationSetBy = Automatic

	column CLM_FREQ_CD
		dataType: int64
		formatString: 0
		lineageTag: 08e47f0c-17c0-44ec-8875-417bc7b8e1fd
		summarizeBy: sum
		sourceColumn: CLM_FREQ_CD

		annotation SummarizationSetBy = Automatic

	column FI_NUM
		dataType: string
		lineageTag: 07b31222-9b36-4271-9aba-49ce62b09b23
		summarizeBy: none
		sourceColumn: FI_NUM

		annotation SummarizationSetBy = Automatic

	column CLM_MDCR_NON_PMT_RSN_CD
		dataType: string
		lineageTag: bee646ef-ba51-4f69-b89f-af680b111891
		summarizeBy: none
		sourceColumn: CLM_MDCR_NON_PMT_RSN_CD

		annotation SummarizationSetBy = Automatic

	column CLM_PMT_AMT
		dataType: double
		lineageTag: 20282e32-9cd7-4158-949d-aefc73812cad
		summarizeBy: sum
		sourceColumn: CLM_PMT_AMT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NCH_PRMRY_PYR_CLM_PD_AMT
		dataType: double
		lineageTag: 95928aa1-f0f3-4c34-81dd-71c28208a5ed
		summarizeBy: sum
		sourceColumn: NCH_PRMRY_PYR_CLM_PD_AMT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NCH_PRMRY_PYR_CD
		dataType: string
		lineageTag: fbcaa076-72f3-4e5f-b225-f9aa445798e4
		summarizeBy: none
		sourceColumn: NCH_PRMRY_PYR_CD

		annotation SummarizationSetBy = Automatic

	column PRVDR_STATE_CD
		dataType: int64
		formatString: 0
		lineageTag: a22fecaf-5e49-4fc2-b63b-f78a61ae4a26
		summarizeBy: sum
		sourceColumn: PRVDR_STATE_CD

		annotation SummarizationSetBy = Automatic

	column ORG_NPI_NUM
		dataType: int64
		formatString: 0
		lineageTag: 7b36cab6-ddc7-4abb-ac09-07ef6dcc190c
		summarizeBy: sum
		sourceColumn: ORG_NPI_NUM

		annotation SummarizationSetBy = Automatic

	column AT_PHYSN_UPIN
		dataType: string
		lineageTag: bccbdec9-9942-47f9-896e-2b56236fffda
		summarizeBy: none
		sourceColumn: AT_PHYSN_UPIN

		annotation SummarizationSetBy = Automatic

	column AT_PHYSN_NPI
		dataType: int64
		formatString: 0
		lineageTag: 0423a503-28a7-4abf-87ba-19c069aa08b3
		summarizeBy: sum
		sourceColumn: AT_PHYSN_NPI

		annotation SummarizationSetBy = Automatic

	column PTNT_DSCHRG_STUS_CD
		dataType: int64
		formatString: 0
		lineageTag: c309dab9-e86a-49f0-84af-26ed9ac10e57
		summarizeBy: sum
		sourceColumn: PTNT_DSCHRG_STUS_CD

		annotation SummarizationSetBy = Automatic

	column CLM_TOT_CHRG_AMT
		dataType: double
		lineageTag: e7939c99-0f42-41cb-acc0-a549e5308a44
		summarizeBy: sum
		sourceColumn: CLM_TOT_CHRG_AMT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NCH_PTNT_STATUS_IND_CD
		dataType: string
		lineageTag: 84381b28-ba41-45fe-bc0c-4c8315d1838e
		summarizeBy: none
		sourceColumn: NCH_PTNT_STATUS_IND_CD

		annotation SummarizationSetBy = Automatic

	column CLM_UTLZTN_DAY_CNT
		dataType: int64
		formatString: 0
		lineageTag: 703bf966-6675-4912-bb00-6ffaad93e263
		summarizeBy: sum
		sourceColumn: CLM_UTLZTN_DAY_CNT

		annotation SummarizationSetBy = Automatic

	column NCH_BENE_DSCHRG_DT
		dataType: dateTime
		formatString: Long Date
		lineageTag: 86ee251c-ca17-4f6a-994d-47de9b829e90
		summarizeBy: none
		sourceColumn: NCH_BENE_DSCHRG_DT

		variation Variation
			isDefault
			relationship: 1a0fcac2-e3ad-4ab4-8ad4-a729164e13f4
			defaultHierarchy: LocalDateTable_93540a5f-b1be-4846-89ce-dc8bb62d7132.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column PRNCPAL_DGNS_CD
		dataType: string
		lineageTag: 22dd49e9-b569-495b-8d2e-808201515d9f
		summarizeBy: none
		sourceColumn: PRNCPAL_DGNS_CD

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD1
		dataType: string
		lineageTag: f66efe98-e1a3-4398-8978-d66189e441ba
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD1

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD2
		dataType: string
		lineageTag: 72044a23-1de3-44e2-9115-88cbd655b614
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD2

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD3
		dataType: string
		lineageTag: 72e127b7-f042-4640-b8f5-39a7b12b4999
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD3

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD4
		dataType: string
		lineageTag: a365c5c9-97c9-45a2-86c7-449e84f6e0ef
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD4

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD5
		dataType: string
		lineageTag: 528ee1d1-45ce-4a2f-a08c-87561f4e1839
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD5

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD6
		dataType: string
		lineageTag: 9fd11fb6-76db-4353-bcca-95ec52a41fec
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD6

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD7
		dataType: string
		lineageTag: 33d8b335-8fb4-471a-86dc-6b2b5c6b33d7
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD7

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD8
		dataType: string
		lineageTag: 1ac4174c-c597-4ab1-8c4a-f7635e052f4a
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD8

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD9
		dataType: string
		lineageTag: 0c23bf5f-df86-41e8-b270-989b4ad8a6db
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD9

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD10
		dataType: string
		lineageTag: 055f2116-2a06-4070-a3ba-06de4937e971
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD10

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD11
		dataType: string
		lineageTag: 77627b93-55b9-4f6a-8bd5-76757a17c757
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD11

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD12
		dataType: string
		lineageTag: c35ded56-b74d-4c2e-a4aa-a9523c46e034
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD12

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD13
		dataType: string
		lineageTag: c8ddb1ff-52de-4518-a82c-6171e8a29bbc
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD13

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD14
		dataType: string
		lineageTag: 08b544cd-7449-4284-a5df-d3b2097540cb
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD14

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD15
		dataType: string
		lineageTag: 9e3da617-8bec-4eca-b8f2-14a0e4e0b9f8
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD15

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD16
		dataType: string
		lineageTag: 1e8eba8f-5937-4633-af0e-7b379da7ea88
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD16

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD17
		dataType: string
		lineageTag: 6a9268f2-7b10-4d03-b59e-2fd797e015c4
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD17

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD18
		dataType: string
		lineageTag: c82c1274-b896-49f8-a740-7a6b112cd105
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD18

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD19
		dataType: string
		lineageTag: 64d560fd-f28e-4f74-9a9b-6c96cbfd1371
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD19

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD20
		dataType: string
		lineageTag: 9a7763a0-55ac-43fc-91c6-8f2c25d539d2
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD20

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD21
		dataType: string
		lineageTag: bde97b15-659e-4c12-a86f-5115c6e3fdd4
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD21

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD22
		dataType: string
		lineageTag: 944bb195-dabc-4697-aed2-9b20f86579ad
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD22

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD23
		dataType: string
		lineageTag: ada63992-73c0-4597-923a-e8c112dae7ec
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD23

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD24
		dataType: string
		lineageTag: 61001939-0594-49c5-846a-f91cf15fdcf6
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD24

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD25
		dataType: string
		lineageTag: d8d2a807-5f1a-4611-8518-13e8f990dc1f
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD25

		annotation SummarizationSetBy = Automatic

	column FST_DGNS_E_CD
		dataType: string
		lineageTag: 776d6ad8-99d4-4255-b039-cbc3152e36e0
		summarizeBy: none
		sourceColumn: FST_DGNS_E_CD

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_E_CD1
		dataType: string
		lineageTag: 3369d273-5abe-4505-b4c8-cc75da74af6a
		summarizeBy: none
		sourceColumn: ICD_DGNS_E_CD1

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_E_CD2
		dataType: string
		lineageTag: 6f50ad00-d099-4e4f-83df-3408354c562d
		summarizeBy: none
		sourceColumn: ICD_DGNS_E_CD2

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_E_CD3
		dataType: string
		lineageTag: 21030a7a-6f4d-4c5b-b452-3f498e879d0e
		summarizeBy: none
		sourceColumn: ICD_DGNS_E_CD3

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_E_CD4
		dataType: string
		lineageTag: 8c6e4e55-3c12-4ec6-a864-1b3ea25dbad8
		summarizeBy: none
		sourceColumn: ICD_DGNS_E_CD4

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_E_CD5
		dataType: string
		lineageTag: 7d75e600-cabf-4d28-b8f5-b25dbf3173b6
		summarizeBy: none
		sourceColumn: ICD_DGNS_E_CD5

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_E_CD6
		dataType: string
		lineageTag: d4e76766-84bf-4b17-8548-48f8d0d154f8
		summarizeBy: none
		sourceColumn: ICD_DGNS_E_CD6

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_E_CD7
		dataType: string
		lineageTag: bed6aace-5755-409a-a54b-55c1876c52fe
		summarizeBy: none
		sourceColumn: ICD_DGNS_E_CD7

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_E_CD8
		dataType: string
		lineageTag: 4390c22d-964c-41f0-b47d-4517a4032783
		summarizeBy: none
		sourceColumn: ICD_DGNS_E_CD8

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_E_CD9
		dataType: string
		lineageTag: afcfc0de-d20b-453a-9eed-37e180cc0946
		summarizeBy: none
		sourceColumn: ICD_DGNS_E_CD9

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_E_CD10
		dataType: string
		lineageTag: e89365d0-d4ff-4426-8d18-27e6e3eb8db2
		summarizeBy: none
		sourceColumn: ICD_DGNS_E_CD10

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_E_CD11
		dataType: string
		lineageTag: 715a739b-2a03-4865-a02b-52c19d90a02c
		summarizeBy: none
		sourceColumn: ICD_DGNS_E_CD11

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_E_CD12
		dataType: string
		lineageTag: 6b58d777-89ea-4de9-aae5-1baa95e882df
		summarizeBy: none
		sourceColumn: ICD_DGNS_E_CD12

		annotation SummarizationSetBy = Automatic

	column CLM_HOSPC_START_DT_ID
		dataType: dateTime
		formatString: Long Date
		lineageTag: 59a51dd3-f7ce-458f-b788-2a7091513b4c
		summarizeBy: none
		sourceColumn: CLM_HOSPC_START_DT_ID

		variation Variation
			isDefault
			relationship: 93564120-b8d0-47a3-86d8-26b93ca9950f
			defaultHierarchy: LocalDateTable_12403a46-992c-4d35-ba7e-6293e1804456.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column BENE_HOSPC_PRD_CNT
		dataType: string
		lineageTag: 1655573c-ca20-40ba-a72d-38c5952103c7
		summarizeBy: none
		sourceColumn: BENE_HOSPC_PRD_CNT

		annotation SummarizationSetBy = Automatic

	column CLAIM_QUERY_CODE
		dataType: int64
		formatString: 0
		lineageTag: 334c4b09-beda-4775-8e60-149424a5c8f1
		summarizeBy: sum
		sourceColumn: CLAIM_QUERY_CODE

		annotation SummarizationSetBy = Automatic

	column CLM_LINE_NUM
		dataType: int64
		formatString: 0
		lineageTag: 976d63aa-de3a-4b43-a542-5aa8d08d7729
		summarizeBy: sum
		sourceColumn: CLM_LINE_NUM

		annotation SummarizationSetBy = Automatic

	column REV_CNTR
		dataType: int64
		formatString: 0
		lineageTag: fe8bbdb9-db74-4fe4-92c9-e3a74fa71c5f
		summarizeBy: sum
		sourceColumn: REV_CNTR

		annotation SummarizationSetBy = Automatic

	column REV_CNTR_DT
		dataType: dateTime
		formatString: Long Date
		lineageTag: e19a3162-c000-4a48-b867-b0d0719eb8a1
		summarizeBy: none
		sourceColumn: REV_CNTR_DT

		variation Variation
			isDefault
			relationship: 7c8c9e55-7bae-47df-b486-c13c4d2596b2
			defaultHierarchy: LocalDateTable_5b814365-6a05-480d-9ae0-6ea145574e2e.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column HCPCS_CD
		dataType: string
		lineageTag: 4472d7c1-80ba-4575-aa10-c19b37326fce
		summarizeBy: none
		sourceColumn: HCPCS_CD

		annotation SummarizationSetBy = Automatic

	column HCPCS_1ST_MDFR_CD
		dataType: string
		lineageTag: 9d617d37-aff6-469a-ab49-5a4d274172e1
		summarizeBy: none
		sourceColumn: HCPCS_1ST_MDFR_CD

		annotation SummarizationSetBy = Automatic

	column HCPCS_2ND_MDFR_CD
		dataType: string
		lineageTag: cef91cdc-366e-4037-b49a-0891a5f3bded
		summarizeBy: none
		sourceColumn: HCPCS_2ND_MDFR_CD

		annotation SummarizationSetBy = Automatic

	column REV_CNTR_UNIT_CNT
		dataType: int64
		formatString: 0
		lineageTag: 39454b88-060a-4b9f-a732-7359f54096a9
		summarizeBy: sum
		sourceColumn: REV_CNTR_UNIT_CNT

		annotation SummarizationSetBy = Automatic

	column REV_CNTR_RATE_AMT
		dataType: double
		lineageTag: f8e6dc25-4b6b-40e0-ac06-45b0a326bf3d
		summarizeBy: sum
		sourceColumn: REV_CNTR_RATE_AMT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column REV_CNTR_PRVDR_PMT_AMT
		dataType: double
		lineageTag: fca81706-0445-49d2-bcc1-4b213fc3414a
		summarizeBy: sum
		sourceColumn: REV_CNTR_PRVDR_PMT_AMT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column REV_CNTR_BENE_PMT_AMT
		dataType: int64
		formatString: 0
		lineageTag: 676ba753-b60d-4be8-a2e2-a98efef74dd7
		summarizeBy: sum
		sourceColumn: REV_CNTR_BENE_PMT_AMT

		annotation SummarizationSetBy = Automatic

	column REV_CNTR_PMT_AMT_AMT
		dataType: double
		lineageTag: b0b617ed-6254-4e6f-b0f6-403f05127a10
		summarizeBy: sum
		sourceColumn: REV_CNTR_PMT_AMT_AMT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column REV_CNTR_TOT_CHRG_AMT
		dataType: double
		lineageTag: 832e11a1-0edd-4726-ba1d-05e7e3081111
		summarizeBy: sum
		sourceColumn: REV_CNTR_TOT_CHRG_AMT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column REV_CNTR_NCVRD_CHRG_AMT
		dataType: double
		lineageTag: 3a7e6b51-5394-4c93-9002-f01dfe35742d
		summarizeBy: sum
		sourceColumn: REV_CNTR_NCVRD_CHRG_AMT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column REV_CNTR_DDCTBL_COINSRNC_CD
		dataType: int64
		formatString: 0
		lineageTag: 13a2c867-a03a-4e45-b542-c9aa8ce7cbce
		summarizeBy: sum
		sourceColumn: REV_CNTR_DDCTBL_COINSRNC_CD

		annotation SummarizationSetBy = Automatic

	column REV_CNTR_NDC_QTY
		dataType: string
		lineageTag: a74f559c-6fba-403e-b3b7-14bdde3fcd41
		summarizeBy: none
		sourceColumn: REV_CNTR_NDC_QTY

		annotation SummarizationSetBy = Automatic

	column REV_CNTR_NDC_QTY_QLFR_CD
		dataType: string
		lineageTag: ea79dcb0-4ac7-4d6f-a8a7-1926eaeb2eed
		summarizeBy: none
		sourceColumn: REV_CNTR_NDC_QTY_QLFR_CD

		annotation SummarizationSetBy = Automatic

	column RNDRNG_PHYSN_UPIN
		dataType: string
		lineageTag: ea137731-ab44-40f1-9434-ee37c3cad9ae
		summarizeBy: none
		sourceColumn: RNDRNG_PHYSN_UPIN

		annotation SummarizationSetBy = Automatic

	column RNDRNG_PHYSN_NPI
		dataType: int64
		formatString: 0
		lineageTag: 6b797cdc-11e7-4218-8770-b6fdab8ecd31
		summarizeBy: sum
		sourceColumn: RNDRNG_PHYSN_NPI

		annotation SummarizationSetBy = Automatic

	partition hospice = m
		mode: import
		source =
				let
				    Source = Folder.Files("C:\Users\dpnsh\Downloads\All FFS Claims"),
				    #"C:\Users\dpnsh\Downloads\All FFS Claims\_hospice csv1" = Source{[#"Folder Path"="C:\Users\dpnsh\Downloads\All FFS Claims\",Name="hospice.csv"]}[Content],
				    #"Imported CSV" = Csv.Document(#"C:\Users\dpnsh\Downloads\All FFS Claims\_hospice csv1",[Delimiter="|", Columns=86, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Imported CSV", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"BENE_ID", Int64.Type}, {"CLM_ID", Int64.Type}, {"NCH_NEAR_LINE_REC_IDENT_CD", type text}, {"NCH_CLM_TYPE_CD", Int64.Type}, {"CLM_FROM_DT", type date}, {"CLM_THRU_DT", type date}, {"NCH_WKLY_PROC_DT", type date}, {"FI_CLM_PROC_DT", type text}, {"PRVDR_NUM", type text}, {"CLM_FAC_TYPE_CD", Int64.Type}, {"CLM_SRVC_CLSFCTN_TYPE_CD", Int64.Type}, {"CLM_FREQ_CD", Int64.Type}, {"FI_NUM", type text}, {"CLM_MDCR_NON_PMT_RSN_CD", type text}, {"CLM_PMT_AMT", type number}, {"NCH_PRMRY_PYR_CLM_PD_AMT", type number}, {"NCH_PRMRY_PYR_CD", type text}, {"PRVDR_STATE_CD", Int64.Type}, {"ORG_NPI_NUM", Int64.Type}, {"AT_PHYSN_UPIN", type text}, {"AT_PHYSN_NPI", Int64.Type}, {"PTNT_DSCHRG_STUS_CD", Int64.Type}, {"CLM_TOT_CHRG_AMT", type number}, {"NCH_PTNT_STATUS_IND_CD", type text}, {"CLM_UTLZTN_DAY_CNT", Int64.Type}, {"NCH_BENE_DSCHRG_DT", type date}, {"PRNCPAL_DGNS_CD", type text}, {"ICD_DGNS_CD1", type text}, {"ICD_DGNS_CD2", type text}, {"ICD_DGNS_CD3", type text}, {"ICD_DGNS_CD4", type text}, {"ICD_DGNS_CD5", type text}, {"ICD_DGNS_CD6", type text}, {"ICD_DGNS_CD7", type text}, {"ICD_DGNS_CD8", type text}, {"ICD_DGNS_CD9", type text}, {"ICD_DGNS_CD10", type text}, {"ICD_DGNS_CD11", type text}, {"ICD_DGNS_CD12", type text}, {"ICD_DGNS_CD13", type text}, {"ICD_DGNS_CD14", type text}, {"ICD_DGNS_CD15", type text}, {"ICD_DGNS_CD16", type text}, {"ICD_DGNS_CD17", type text}, {"ICD_DGNS_CD18", type text}, {"ICD_DGNS_CD19", type text}, {"ICD_DGNS_CD20", type text}, {"ICD_DGNS_CD21", type text}, {"ICD_DGNS_CD22", type text}, {"ICD_DGNS_CD23", type text}, {"ICD_DGNS_CD24", type text}, {"ICD_DGNS_CD25", type text}, {"FST_DGNS_E_CD", type text}, {"ICD_DGNS_E_CD1", type text}, {"ICD_DGNS_E_CD2", type text}, {"ICD_DGNS_E_CD3", type text}, {"ICD_DGNS_E_CD4", type text}, {"ICD_DGNS_E_CD5", type text}, {"ICD_DGNS_E_CD6", type text}, {"ICD_DGNS_E_CD7", type text}, {"ICD_DGNS_E_CD8", type text}, {"ICD_DGNS_E_CD9", type text}, {"ICD_DGNS_E_CD10", type text}, {"ICD_DGNS_E_CD11", type text}, {"ICD_DGNS_E_CD12", type text}, {"CLM_HOSPC_START_DT_ID", type date}, {"BENE_HOSPC_PRD_CNT", type text}, {"CLAIM_QUERY_CODE", Int64.Type}, {"CLM_LINE_NUM", Int64.Type}, {"REV_CNTR", Int64.Type}, {"REV_CNTR_DT", type date}, {"HCPCS_CD", type text}, {"HCPCS_1ST_MDFR_CD", type text}, {"HCPCS_2ND_MDFR_CD", type text}, {"REV_CNTR_UNIT_CNT", Int64.Type}, {"REV_CNTR_RATE_AMT", type number}, {"REV_CNTR_PRVDR_PMT_AMT", type number}, {"REV_CNTR_BENE_PMT_AMT", Int64.Type}, {"REV_CNTR_PMT_AMT_AMT", type number}, {"REV_CNTR_TOT_CHRG_AMT", type number}, {"REV_CNTR_NCVRD_CHRG_AMT", type number}, {"REV_CNTR_DDCTBL_COINSRNC_CD", Int64.Type}, {"REV_CNTR_NDC_QTY", type text}, {"REV_CNTR_NDC_QTY_QLFR_CD", type text}, {"RNDRNG_PHYSN_UPIN", type text}, {"RNDRNG_PHYSN_NPI", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

