table snf
	lineageTag: df2e6788-d083-4a53-a611-20dbfd0e5984

	column BENE_ID
		dataType: int64
		formatString: 0
		lineageTag: 3e48ac37-60d9-4fa2-b141-7f9927eddcc2
		summarizeBy: count
		sourceColumn: BENE_ID

		annotation SummarizationSetBy = Automatic

	column CLM_ID
		dataType: int64
		formatString: 0
		lineageTag: 36b95c95-49d5-47ef-81ba-347d1f76f118
		summarizeBy: count
		sourceColumn: CLM_ID

		annotation SummarizationSetBy = Automatic

	column NCH_NEAR_LINE_REC_IDENT_CD
		dataType: string
		lineageTag: 878bfc81-b744-434b-a930-d78359a447fa
		summarizeBy: none
		sourceColumn: NCH_NEAR_LINE_REC_IDENT_CD

		annotation SummarizationSetBy = Automatic

	column NCH_CLM_TYPE_CD
		dataType: int64
		formatString: 0
		lineageTag: 963bf82f-1b78-4373-bd18-0d62f5bb1de5
		summarizeBy: sum
		sourceColumn: NCH_CLM_TYPE_CD

		annotation SummarizationSetBy = Automatic

	column CLM_FROM_DT
		dataType: dateTime
		formatString: Long Date
		lineageTag: 2767cfc1-c5e1-4276-b4e0-74cc13d94139
		summarizeBy: none
		sourceColumn: CLM_FROM_DT

		variation Variation
			isDefault
			relationship: 14baa42e-fb18-4619-899f-41dee9de3fe5
			defaultHierarchy: LocalDateTable_0198f89b-fdec-4361-8cfa-2ebdee3f9047.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CLM_THRU_DT
		dataType: dateTime
		formatString: Long Date
		lineageTag: f0c3d50d-ac06-4758-a61d-009f5183c5fa
		summarizeBy: none
		sourceColumn: CLM_THRU_DT

		variation Variation
			isDefault
			relationship: c9ac7ecd-1f53-4948-8f09-e6afafcb6114
			defaultHierarchy: LocalDateTable_816242da-6415-4798-a989-5e4afd60fc1f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column NCH_WKLY_PROC_DT
		dataType: dateTime
		formatString: Long Date
		lineageTag: c069251c-a7da-4144-856b-7a5826de19d9
		summarizeBy: none
		sourceColumn: NCH_WKLY_PROC_DT

		variation Variation
			isDefault
			relationship: bf5f6a4d-3ef2-4c57-87f0-5180fb4b9bc2
			defaultHierarchy: LocalDateTable_5083e219-43d7-4a99-b231-c51b14d5dac5.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column FI_CLM_PROC_DT
		dataType: string
		lineageTag: cf1cf8a7-e6a0-4920-96a5-62eaa579c75b
		summarizeBy: none
		sourceColumn: FI_CLM_PROC_DT

		annotation SummarizationSetBy = Automatic

	column CLAIM_QUERY_CODE
		dataType: int64
		formatString: 0
		lineageTag: c22fd7c7-082e-4284-a95b-d44363fb5fd5
		summarizeBy: sum
		sourceColumn: CLAIM_QUERY_CODE

		annotation SummarizationSetBy = Automatic

	column PRVDR_NUM
		dataType: string
		lineageTag: 94a3c1fc-1fcf-4d48-aa1c-198667fa16c6
		summarizeBy: none
		sourceColumn: PRVDR_NUM

		annotation SummarizationSetBy = Automatic

	column CLM_FAC_TYPE_CD
		dataType: int64
		formatString: 0
		lineageTag: df327b81-1267-4a89-a366-85bcb41c4e45
		summarizeBy: sum
		sourceColumn: CLM_FAC_TYPE_CD

		annotation SummarizationSetBy = Automatic

	column CLM_SRVC_CLSFCTN_TYPE_CD
		dataType: int64
		formatString: 0
		lineageTag: 10139071-f762-448a-a729-440f8f0828d0
		summarizeBy: sum
		sourceColumn: CLM_SRVC_CLSFCTN_TYPE_CD

		annotation SummarizationSetBy = Automatic

	column CLM_FREQ_CD
		dataType: int64
		formatString: 0
		lineageTag: db4d799b-5664-4558-aa90-f96807aa083f
		summarizeBy: sum
		sourceColumn: CLM_FREQ_CD

		annotation SummarizationSetBy = Automatic

	column FI_NUM
		dataType: string
		lineageTag: 7c9922c3-19e5-4875-9fa3-06bae992245f
		summarizeBy: none
		sourceColumn: FI_NUM

		annotation SummarizationSetBy = Automatic

	column CLM_MDCR_NON_PMT_RSN_CD
		dataType: string
		lineageTag: fcec0b09-62b2-4d32-ac0a-732a0d4c1861
		summarizeBy: none
		sourceColumn: CLM_MDCR_NON_PMT_RSN_CD

		annotation SummarizationSetBy = Automatic

	column CLM_PMT_AMT
		dataType: double
		lineageTag: 4ed8c6d1-f72f-4e81-8a94-9366b1985b39
		summarizeBy: sum
		sourceColumn: CLM_PMT_AMT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NCH_PRMRY_PYR_CLM_PD_AMT
		dataType: double
		lineageTag: 0d94ccb0-3550-4a58-aabb-b36fda5624d1
		summarizeBy: sum
		sourceColumn: NCH_PRMRY_PYR_CLM_PD_AMT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NCH_PRMRY_PYR_CD
		dataType: string
		lineageTag: 3c46c283-fe13-4720-844d-456e063bc4bc
		summarizeBy: none
		sourceColumn: NCH_PRMRY_PYR_CD

		annotation SummarizationSetBy = Automatic

	column FI_CLM_ACTN_CD
		dataType: string
		lineageTag: 8d039dac-21f6-4bbc-96d4-77a1ba7387f4
		summarizeBy: none
		sourceColumn: FI_CLM_ACTN_CD

		annotation SummarizationSetBy = Automatic

	column PRVDR_STATE_CD
		dataType: int64
		formatString: 0
		lineageTag: 56a393c4-13f8-4855-82bd-de47cacd247c
		summarizeBy: sum
		sourceColumn: PRVDR_STATE_CD

		annotation SummarizationSetBy = Automatic

	column ORG_NPI_NUM
		dataType: int64
		formatString: 0
		lineageTag: 580e262a-e1b2-49ac-98ae-f5c0ede82f50
		summarizeBy: sum
		sourceColumn: ORG_NPI_NUM

		annotation SummarizationSetBy = Automatic

	column AT_PHYSN_UPIN
		dataType: string
		lineageTag: 13365337-e1ed-40c5-99af-781d1cb47a10
		summarizeBy: none
		sourceColumn: AT_PHYSN_UPIN

		annotation SummarizationSetBy = Automatic

	column AT_PHYSN_NPI
		dataType: int64
		formatString: 0
		lineageTag: c7ddeb01-7a00-4725-a8f0-375c6c45c37e
		summarizeBy: sum
		sourceColumn: AT_PHYSN_NPI

		annotation SummarizationSetBy = Automatic

	column OP_PHYSN_UPIN
		dataType: string
		lineageTag: 62bdb429-a221-4f3a-a818-88d6f3388f3d
		summarizeBy: none
		sourceColumn: OP_PHYSN_UPIN

		annotation SummarizationSetBy = Automatic

	column OP_PHYSN_NPI
		dataType: int64
		formatString: 0
		lineageTag: 59b1e771-de08-4f26-9343-77ae35fc9203
		summarizeBy: sum
		sourceColumn: OP_PHYSN_NPI

		annotation SummarizationSetBy = Automatic

	column OT_PHYSN_UPIN
		dataType: string
		lineageTag: 03ea9b78-890e-4f4c-b377-b5d28966112b
		summarizeBy: none
		sourceColumn: OT_PHYSN_UPIN

		annotation SummarizationSetBy = Automatic

	column OT_PHYSN_NPI
		dataType: string
		lineageTag: 7f66f91e-2d52-4854-9d58-fcf121150940
		summarizeBy: none
		sourceColumn: OT_PHYSN_NPI

		annotation SummarizationSetBy = Automatic

	column CLM_MCO_PD_SW
		dataType: int64
		formatString: 0
		lineageTag: 3f92f354-c89f-4a48-b609-5483352819ce
		summarizeBy: sum
		sourceColumn: CLM_MCO_PD_SW

		annotation SummarizationSetBy = Automatic

	column PTNT_DSCHRG_STUS_CD
		dataType: int64
		formatString: 0
		lineageTag: 8bab9d04-21fa-47e3-9680-c79d446c6f3b
		summarizeBy: sum
		sourceColumn: PTNT_DSCHRG_STUS_CD

		annotation SummarizationSetBy = Automatic

	column CLM_PPS_IND_CD
		dataType: string
		lineageTag: aba5d206-0388-4094-a2cc-19838d4f1b2a
		summarizeBy: none
		sourceColumn: CLM_PPS_IND_CD

		annotation SummarizationSetBy = Automatic

	column CLM_TOT_CHRG_AMT
		dataType: double
		lineageTag: 2c2326a9-abc5-4a82-8d95-d1be5a93ac19
		summarizeBy: sum
		sourceColumn: CLM_TOT_CHRG_AMT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CLM_ADMSN_DT
		dataType: dateTime
		formatString: Long Date
		lineageTag: e336e76e-c00f-4ffb-93ed-49fd8d62d97a
		summarizeBy: none
		sourceColumn: CLM_ADMSN_DT

		variation Variation
			isDefault
			relationship: b913f012-397b-4b76-a7d0-5a126d328b39
			defaultHierarchy: LocalDateTable_b259731e-e79b-43e9-85fb-394e65a66fcb.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CLM_IP_ADMSN_TYPE_CD
		dataType: int64
		formatString: 0
		lineageTag: 546c7bcd-1c40-483e-a173-c8729fe52ffa
		summarizeBy: sum
		sourceColumn: CLM_IP_ADMSN_TYPE_CD

		annotation SummarizationSetBy = Automatic

	column CLM_SRC_IP_ADMSN_CD
		dataType: int64
		formatString: 0
		lineageTag: 0e90e4e8-3597-44ec-b4d2-1587378281ea
		summarizeBy: sum
		sourceColumn: CLM_SRC_IP_ADMSN_CD

		annotation SummarizationSetBy = Automatic

	column NCH_PTNT_STATUS_IND_CD
		dataType: string
		lineageTag: c5454483-3201-4e8f-acc2-911009c282cd
		summarizeBy: none
		sourceColumn: NCH_PTNT_STATUS_IND_CD

		annotation SummarizationSetBy = Automatic

	column NCH_BENE_IP_DDCTBL_AMT
		dataType: int64
		formatString: 0
		lineageTag: 509a6a63-514b-437a-8a3f-7e4ebb08f114
		summarizeBy: sum
		sourceColumn: NCH_BENE_IP_DDCTBL_AMT

		annotation SummarizationSetBy = Automatic

	column NCH_BENE_PTA_COINSRNC_LBLTY_AM
		dataType: double
		lineageTag: ea829dea-ca94-40f3-beb6-b79b2ae6de74
		summarizeBy: sum
		sourceColumn: NCH_BENE_PTA_COINSRNC_LBLTY_AM

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NCH_BENE_BLOOD_DDCTBL_LBLTY_AM
		dataType: int64
		formatString: 0
		lineageTag: 5e8b6536-4163-4b1c-b91a-18af0d280b1b
		summarizeBy: sum
		sourceColumn: NCH_BENE_BLOOD_DDCTBL_LBLTY_AM

		annotation SummarizationSetBy = Automatic

	column NCH_IP_NCVRD_CHRG_AMT
		dataType: double
		lineageTag: 3665d044-44a3-45be-b4e9-21166a71ab8f
		summarizeBy: sum
		sourceColumn: NCH_IP_NCVRD_CHRG_AMT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NCH_IP_TOT_DDCTN_AMT
		dataType: double
		lineageTag: c28ed64d-54ad-4966-8176-0648422d58e1
		summarizeBy: sum
		sourceColumn: NCH_IP_TOT_DDCTN_AMT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CLM_PPS_CPTL_FSP_AMT
		dataType: int64
		formatString: 0
		lineageTag: 1ac1ade8-7d99-4833-930b-66880a6e2f5a
		summarizeBy: sum
		sourceColumn: CLM_PPS_CPTL_FSP_AMT

		annotation SummarizationSetBy = Automatic

	column CLM_PPS_CPTL_OUTLIER_AMT
		dataType: int64
		formatString: 0
		lineageTag: 15a3a1f5-3364-4b19-8852-26527f782dd9
		summarizeBy: sum
		sourceColumn: CLM_PPS_CPTL_OUTLIER_AMT

		annotation SummarizationSetBy = Automatic

	column CLM_PPS_CPTL_DSPRPRTNT_SHR_AMT
		dataType: int64
		formatString: 0
		lineageTag: a438e8dc-6389-40ef-b9d2-0cc4eb0bd4e1
		summarizeBy: sum
		sourceColumn: CLM_PPS_CPTL_DSPRPRTNT_SHR_AMT

		annotation SummarizationSetBy = Automatic

	column CLM_PPS_CPTL_IME_AMT
		dataType: int64
		formatString: 0
		lineageTag: bd6a56f5-9435-456d-8040-d3395eab8c19
		summarizeBy: sum
		sourceColumn: CLM_PPS_CPTL_IME_AMT

		annotation SummarizationSetBy = Automatic

	column CLM_PPS_CPTL_EXCPTN_AMT
		dataType: int64
		formatString: 0
		lineageTag: 708afc81-ddcd-4cba-b8c0-f8facfa3e6c6
		summarizeBy: sum
		sourceColumn: CLM_PPS_CPTL_EXCPTN_AMT

		annotation SummarizationSetBy = Automatic

	column CLM_PPS_OLD_CPTL_HLD_HRMLS_AMT
		dataType: int64
		formatString: 0
		lineageTag: 59b466c4-74e4-4564-a861-840bef88d222
		summarizeBy: sum
		sourceColumn: CLM_PPS_OLD_CPTL_HLD_HRMLS_AMT

		annotation SummarizationSetBy = Automatic

	column CLM_UTLZTN_DAY_CNT
		dataType: int64
		formatString: 0
		lineageTag: 677a7df7-d9be-4fd1-927d-ab01b273ba76
		summarizeBy: sum
		sourceColumn: CLM_UTLZTN_DAY_CNT

		annotation SummarizationSetBy = Automatic

	column BENE_TOT_COINSRNC_DAYS_CNT
		dataType: int64
		formatString: 0
		lineageTag: 250668a4-0624-4082-b667-fad6c3ce9ca0
		summarizeBy: sum
		sourceColumn: BENE_TOT_COINSRNC_DAYS_CNT

		annotation SummarizationSetBy = Automatic

	column CLM_NON_UTLZTN_DAYS_CNT
		dataType: int64
		formatString: 0
		lineageTag: c3e4bf99-c642-4db7-a9c8-86e878bf6fcb
		summarizeBy: sum
		sourceColumn: CLM_NON_UTLZTN_DAYS_CNT

		annotation SummarizationSetBy = Automatic

	column NCH_BLOOD_PNTS_FRNSHD_QTY
		dataType: int64
		formatString: 0
		lineageTag: 652232d5-c87f-45e5-8571-66b186e0f8ca
		summarizeBy: sum
		sourceColumn: NCH_BLOOD_PNTS_FRNSHD_QTY

		annotation SummarizationSetBy = Automatic

	column NCH_QLFYD_STAY_FROM_DT
		dataType: string
		lineageTag: ebfcf032-5cfc-4f48-8932-5b836253c093
		summarizeBy: none
		sourceColumn: NCH_QLFYD_STAY_FROM_DT

		annotation SummarizationSetBy = Automatic

	column NCH_QLFYD_STAY_THRU_DT
		dataType: string
		lineageTag: ae756d73-6a2d-4857-9c41-f206018a4806
		summarizeBy: none
		sourceColumn: NCH_QLFYD_STAY_THRU_DT

		annotation SummarizationSetBy = Automatic

	column NCH_VRFD_NCVRD_STAY_FROM_DT
		dataType: string
		lineageTag: 5b7d0af3-93e7-4a91-958f-1157cd4bcbda
		summarizeBy: none
		sourceColumn: NCH_VRFD_NCVRD_STAY_FROM_DT

		annotation SummarizationSetBy = Automatic

	column NCH_VRFD_NCVRD_STAY_THRU_DT
		dataType: string
		lineageTag: 03970165-44f5-4617-8ef1-3445724d339b
		summarizeBy: none
		sourceColumn: NCH_VRFD_NCVRD_STAY_THRU_DT

		annotation SummarizationSetBy = Automatic

	column NCH_ACTV_OR_CVRD_LVL_CARE_THRU
		dataType: string
		lineageTag: af6238eb-9488-4640-815b-5b189093bb9f
		summarizeBy: none
		sourceColumn: NCH_ACTV_OR_CVRD_LVL_CARE_THRU

		annotation SummarizationSetBy = Automatic

	column NCH_BENE_MDCR_BNFTS_EXHTD_DT_I
		dataType: string
		lineageTag: 67321062-780d-4f36-adf9-c7a6f3df6e9a
		summarizeBy: none
		sourceColumn: NCH_BENE_MDCR_BNFTS_EXHTD_DT_I

		annotation SummarizationSetBy = Automatic

	column NCH_BENE_DSCHRG_DT
		dataType: dateTime
		formatString: Long Date
		lineageTag: ab6ab3a7-37c4-4a0c-ac76-a4d1c7c6d866
		summarizeBy: none
		sourceColumn: NCH_BENE_DSCHRG_DT

		variation Variation
			isDefault
			relationship: 30557dbb-c3f1-4afe-aee4-109e38425baf
			defaultHierarchy: LocalDateTable_434d60ad-2aab-4b39-9fd0-8dbe2fe39667.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CLM_DRG_CD
		dataType: int64
		formatString: 0
		lineageTag: efeccf2a-3d0c-4c06-9255-1aaa33dff288
		summarizeBy: sum
		sourceColumn: CLM_DRG_CD

		annotation SummarizationSetBy = Automatic

	column ADMTG_DGNS_CD
		dataType: string
		lineageTag: 20bb0c19-ecd0-45ee-8577-bd632f970096
		summarizeBy: none
		sourceColumn: ADMTG_DGNS_CD

		annotation SummarizationSetBy = Automatic

	column PRNCPAL_DGNS_CD
		dataType: string
		lineageTag: 7f931c37-b8b4-4c7e-ad82-eea71296ea41
		summarizeBy: none
		sourceColumn: PRNCPAL_DGNS_CD

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD1
		dataType: string
		lineageTag: 17a598a6-7f70-41b7-ab17-7790969b1d67
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD1

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD2
		dataType: string
		lineageTag: a3182568-133d-44fc-b60f-bc6abf2b6bee
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD2

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD3
		dataType: string
		lineageTag: 0c0d9ca1-1b1b-46ac-a4f0-f1b665fda6e6
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD3

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD4
		dataType: string
		lineageTag: 4beada3a-091a-4d63-ad91-2f71ef8a8261
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD4

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD5
		dataType: string
		lineageTag: c68021c2-9f05-43ba-b82d-eb8e061234c2
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD5

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD6
		dataType: string
		lineageTag: 432aaf01-d58e-4a14-9712-25e9f40f65db
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD6

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD7
		dataType: string
		lineageTag: c513512e-6406-442b-a7a0-249cda5f1ec5
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD7

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD8
		dataType: string
		lineageTag: 15f58d09-4c79-4261-b45e-70e320d6da7c
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD8

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD9
		dataType: string
		lineageTag: 0a5fd2a2-2f40-48c5-9ce3-5923234158c5
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD9

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD10
		dataType: string
		lineageTag: dafc53d6-5656-46d6-9b66-d1dda65587f5
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD10

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD11
		dataType: string
		lineageTag: af3cbf12-10b0-48aa-be69-8ff1dd7ef93f
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD11

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD12
		dataType: string
		lineageTag: a1da13fe-1042-4043-b0c8-5603d74a1aeb
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD12

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD13
		dataType: string
		lineageTag: acfad8a1-c995-4e6f-9575-cd009c284f4e
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD13

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD14
		dataType: string
		lineageTag: 41d5dd5a-8d3c-46ac-a02c-d67e543a7a96
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD14

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD15
		dataType: string
		lineageTag: 34b70624-0bc8-41c9-9a38-30f2210774e3
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD15

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD16
		dataType: string
		lineageTag: 7401a7ac-e4d3-468a-bb29-9c0705443901
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD16

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD17
		dataType: string
		lineageTag: cfcc125a-7e4e-450b-9eb6-1a1420887ce4
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD17

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD18
		dataType: string
		lineageTag: 8df57626-02e3-4f0f-b4f6-c403fcaf5285
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD18

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD19
		dataType: string
		lineageTag: 690af366-b09d-49f1-9e63-65f5f791aae8
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD19

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD20
		dataType: string
		lineageTag: 4248081d-67bf-4a87-a7b2-8d5abe5387e7
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD20

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD21
		dataType: string
		lineageTag: 76c44768-2959-4c34-8d82-8ee112ac2db0
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD21

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD22
		dataType: string
		lineageTag: 6e74eacf-5094-4fc7-b11b-b9ca2460f992
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD22

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD23
		dataType: string
		lineageTag: 631388b2-c039-4497-9a1b-4651681bb6c1
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD23

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD24
		dataType: string
		lineageTag: 3df0d98f-4b6d-4f83-908e-ed92850d0c08
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD24

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_CD25
		dataType: string
		lineageTag: e1e2249c-9dee-4edc-b132-77cf4da51a36
		summarizeBy: none
		sourceColumn: ICD_DGNS_CD25

		annotation SummarizationSetBy = Automatic

	column FST_DGNS_E_CD
		dataType: string
		lineageTag: f64c1362-c3cf-4910-a105-c3ede61b1cf7
		summarizeBy: none
		sourceColumn: FST_DGNS_E_CD

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_E_CD1
		dataType: string
		lineageTag: d858bc3e-058e-4a8d-a0c3-b3903d2c5241
		summarizeBy: none
		sourceColumn: ICD_DGNS_E_CD1

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_E_CD2
		dataType: string
		lineageTag: b56316e0-75bd-44fe-ab02-e9be9e1652f4
		summarizeBy: none
		sourceColumn: ICD_DGNS_E_CD2

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_E_CD3
		dataType: string
		lineageTag: 4ee2711a-d4fa-4080-9838-1356537f12ac
		summarizeBy: none
		sourceColumn: ICD_DGNS_E_CD3

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_E_CD4
		dataType: string
		lineageTag: 0d578065-8ba2-426d-889b-43f7a4f89f43
		summarizeBy: none
		sourceColumn: ICD_DGNS_E_CD4

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_E_CD5
		dataType: string
		lineageTag: e709bbfc-b9e6-4ca4-a269-72d56e3629a6
		summarizeBy: none
		sourceColumn: ICD_DGNS_E_CD5

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_E_CD6
		dataType: string
		lineageTag: fd48d880-00da-4279-804a-455ee23772d5
		summarizeBy: none
		sourceColumn: ICD_DGNS_E_CD6

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_E_CD7
		dataType: string
		lineageTag: 43c900ca-9a45-40e1-94e2-2042c9f987d3
		summarizeBy: none
		sourceColumn: ICD_DGNS_E_CD7

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_E_CD8
		dataType: string
		lineageTag: 72ba8511-68d9-4b03-87bf-09a4b55ac5d2
		summarizeBy: none
		sourceColumn: ICD_DGNS_E_CD8

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_E_CD9
		dataType: string
		lineageTag: 791f5069-31e0-4068-ad72-4696fe11c313
		summarizeBy: none
		sourceColumn: ICD_DGNS_E_CD9

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_E_CD10
		dataType: string
		lineageTag: 7e11265a-d0ac-429b-b1c4-218624997442
		summarizeBy: none
		sourceColumn: ICD_DGNS_E_CD10

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_E_CD11
		dataType: string
		lineageTag: 5a7093da-c7d0-4183-a556-05583724d9ea
		summarizeBy: none
		sourceColumn: ICD_DGNS_E_CD11

		annotation SummarizationSetBy = Automatic

	column ICD_DGNS_E_CD12
		dataType: string
		lineageTag: ece5257a-8b22-41f4-a3d8-c4c568e701c0
		summarizeBy: none
		sourceColumn: ICD_DGNS_E_CD12

		annotation SummarizationSetBy = Automatic

	column ICD_PRCDR_CD1
		dataType: string
		lineageTag: 20d7590b-bba9-4d5a-b02a-54cb91a7a2d3
		summarizeBy: none
		sourceColumn: ICD_PRCDR_CD1

		annotation SummarizationSetBy = Automatic

	column PRCDR_DT1
		dataType: dateTime
		formatString: Long Date
		lineageTag: 487e12eb-67a6-4e96-8dee-8842d2584a64
		summarizeBy: none
		sourceColumn: PRCDR_DT1

		variation Variation
			isDefault
			relationship: 65087fd9-2e0a-4d1d-b1bd-d894fc0fd715
			defaultHierarchy: LocalDateTable_67849f58-e120-4390-baa8-c966ead4ef87.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ICD_PRCDR_CD2
		dataType: string
		lineageTag: 7409e497-f97a-4a51-9f6c-27fbdac829cb
		summarizeBy: none
		sourceColumn: ICD_PRCDR_CD2

		annotation SummarizationSetBy = Automatic

	column PRCDR_DT2
		dataType: dateTime
		formatString: Long Date
		lineageTag: e03d5151-24ff-4cb1-98e6-2e93e390dade
		summarizeBy: none
		sourceColumn: PRCDR_DT2

		variation Variation
			isDefault
			relationship: 7b3fa010-258e-483c-a42b-d8933286aae3
			defaultHierarchy: LocalDateTable_cc03a9e0-ef51-4de3-ae47-10f9c1606c71.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ICD_PRCDR_CD3
		dataType: string
		lineageTag: 9ace3840-4d5b-40c1-a92b-34805126672f
		summarizeBy: none
		sourceColumn: ICD_PRCDR_CD3

		annotation SummarizationSetBy = Automatic

	column PRCDR_DT3
		dataType: dateTime
		formatString: Long Date
		lineageTag: cbe32c2d-3477-4458-be35-5f16cfd211aa
		summarizeBy: none
		sourceColumn: PRCDR_DT3

		variation Variation
			isDefault
			relationship: e4604dd9-3e78-40c7-902b-618071dddb8d
			defaultHierarchy: LocalDateTable_65c0bf9a-1e56-48ef-8d4a-7d024feb95cb.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ICD_PRCDR_CD4
		dataType: string
		lineageTag: c393a5f6-cbc2-4a37-94b7-8ce1c21647e2
		summarizeBy: none
		sourceColumn: ICD_PRCDR_CD4

		annotation SummarizationSetBy = Automatic

	column PRCDR_DT4
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8206f426-bdad-45f5-8727-5db7f29fa48d
		summarizeBy: none
		sourceColumn: PRCDR_DT4

		variation Variation
			isDefault
			relationship: 943dcbb2-3536-4ff9-9d4c-db44096399b9
			defaultHierarchy: LocalDateTable_8cfa7854-0f53-4862-91b9-c9255873015c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ICD_PRCDR_CD5
		dataType: string
		lineageTag: 5e533fc0-cc06-44ab-a067-ddb24220359d
		summarizeBy: none
		sourceColumn: ICD_PRCDR_CD5

		annotation SummarizationSetBy = Automatic

	column PRCDR_DT5
		dataType: dateTime
		formatString: Long Date
		lineageTag: 78a4deab-78df-4d29-87ff-de6d17dfd1ea
		summarizeBy: none
		sourceColumn: PRCDR_DT5

		variation Variation
			isDefault
			relationship: c8fd855d-363a-4e46-827d-e995bb7a653b
			defaultHierarchy: LocalDateTable_b6c03e67-9a4d-497c-b1c9-37e706269156.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ICD_PRCDR_CD6
		dataType: string
		lineageTag: e6d7d620-7a45-4d3e-b818-f1f7f2ab9876
		summarizeBy: none
		sourceColumn: ICD_PRCDR_CD6

		annotation SummarizationSetBy = Automatic

	column PRCDR_DT6
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6b81939d-a3cd-49b9-b2d6-83e2bd047831
		summarizeBy: none
		sourceColumn: PRCDR_DT6

		variation Variation
			isDefault
			relationship: 10cd209b-d664-42d2-b77a-1f6ad1b8fd80
			defaultHierarchy: LocalDateTable_42491678-5415-4360-bbf3-f7e5bea42053.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ICD_PRCDR_CD7
		dataType: string
		lineageTag: 2f330149-202d-4b24-bfd7-2a014e1fd8f8
		summarizeBy: none
		sourceColumn: ICD_PRCDR_CD7

		annotation SummarizationSetBy = Automatic

	column PRCDR_DT7
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9c6a89cf-2dff-4b93-899b-a66b8deda733
		summarizeBy: none
		sourceColumn: PRCDR_DT7

		variation Variation
			isDefault
			relationship: bff5f948-107e-4a64-b217-d75d2ad6c360
			defaultHierarchy: LocalDateTable_d3d38fce-4ba7-42ee-b1cb-17f0c60d1c77.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ICD_PRCDR_CD8
		dataType: string
		lineageTag: a53484e3-5fe2-4015-b567-ba5c4d3e7fcf
		summarizeBy: none
		sourceColumn: ICD_PRCDR_CD8

		annotation SummarizationSetBy = Automatic

	column PRCDR_DT8
		dataType: dateTime
		formatString: Long Date
		lineageTag: 002a5fd8-a0e7-45a0-8a2f-5f3895744240
		summarizeBy: none
		sourceColumn: PRCDR_DT8

		variation Variation
			isDefault
			relationship: 7dce5bef-a69f-4997-96f9-3d6dfe6054e6
			defaultHierarchy: LocalDateTable_b32d4291-e358-468d-9942-be074c5f49dc.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ICD_PRCDR_CD9
		dataType: string
		lineageTag: 8903efa5-8fa5-460a-bf1b-c7adb30f7a96
		summarizeBy: none
		sourceColumn: ICD_PRCDR_CD9

		annotation SummarizationSetBy = Automatic

	column PRCDR_DT9
		dataType: dateTime
		formatString: Long Date
		lineageTag: e4736a44-47d3-49c5-bf5f-0a70b027dc62
		summarizeBy: none
		sourceColumn: PRCDR_DT9

		variation Variation
			isDefault
			relationship: c6570805-7d13-49ea-b7a5-fcbfa20dc0f9
			defaultHierarchy: LocalDateTable_e800eb58-d82a-4e50-a717-8724a9324312.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ICD_PRCDR_CD10
		dataType: string
		lineageTag: d0aeb746-34c0-4793-a832-9ce768f76cd5
		summarizeBy: none
		sourceColumn: ICD_PRCDR_CD10

		annotation SummarizationSetBy = Automatic

	column PRCDR_DT10
		dataType: dateTime
		formatString: Long Date
		lineageTag: 69ce1000-963c-431a-888c-7e89385b3f14
		summarizeBy: none
		sourceColumn: PRCDR_DT10

		variation Variation
			isDefault
			relationship: 9809253d-09b5-4403-9d9e-6b5ad08a0e2e
			defaultHierarchy: LocalDateTable_fd63a02f-b837-4c8a-8343-d6afe2ba1eab.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ICD_PRCDR_CD11
		dataType: string
		lineageTag: 83e3ac8b-1389-4306-88ff-eaa041f9ad1f
		summarizeBy: none
		sourceColumn: ICD_PRCDR_CD11

		annotation SummarizationSetBy = Automatic

	column PRCDR_DT11
		dataType: dateTime
		formatString: Long Date
		lineageTag: f46cd0dc-f257-40ee-b71c-c8cb9f91bc84
		summarizeBy: none
		sourceColumn: PRCDR_DT11

		variation Variation
			isDefault
			relationship: b35e5cba-1f46-458d-899f-77366b3bd857
			defaultHierarchy: LocalDateTable_7ae63bbe-246b-49d6-8dff-349b344f575b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ICD_PRCDR_CD12
		dataType: string
		lineageTag: 9bd36659-8a69-475d-8806-8b2f53ea67ec
		summarizeBy: none
		sourceColumn: ICD_PRCDR_CD12

		annotation SummarizationSetBy = Automatic

	column PRCDR_DT12
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5b3abefe-cece-4a31-a463-f49704f9092f
		summarizeBy: none
		sourceColumn: PRCDR_DT12

		variation Variation
			isDefault
			relationship: daaf7322-d87e-4378-bf7c-3be754fd8376
			defaultHierarchy: LocalDateTable_c902bd31-10c1-4a81-b134-8404ec834ca0.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ICD_PRCDR_CD13
		dataType: string
		lineageTag: 7544b6c6-a274-4ead-af9c-afa6e8280f24
		summarizeBy: none
		sourceColumn: ICD_PRCDR_CD13

		annotation SummarizationSetBy = Automatic

	column PRCDR_DT13
		dataType: dateTime
		formatString: Long Date
		lineageTag: 70dd81a3-e4e4-4d35-8a4f-7623475a9a39
		summarizeBy: none
		sourceColumn: PRCDR_DT13

		variation Variation
			isDefault
			relationship: 4c1e2653-369c-4b07-807f-e704b3598e2e
			defaultHierarchy: LocalDateTable_6a390dce-9d7d-442e-b418-f5c920c85d95.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ICD_PRCDR_CD14
		dataType: string
		lineageTag: 5ef1ca10-a712-4d59-8475-ddc1dc0ac2e6
		summarizeBy: none
		sourceColumn: ICD_PRCDR_CD14

		annotation SummarizationSetBy = Automatic

	column PRCDR_DT14
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4f997ac1-6b50-4926-a79a-9c87c527e30f
		summarizeBy: none
		sourceColumn: PRCDR_DT14

		variation Variation
			isDefault
			relationship: 6ce44e00-2444-40b7-a235-78c70dcef3d6
			defaultHierarchy: LocalDateTable_9645cc2b-6cf6-42cb-a01c-bc4a8517f159.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ICD_PRCDR_CD15
		dataType: string
		lineageTag: 5c8b3ad1-5640-41cf-9551-aee05b08c9ac
		summarizeBy: none
		sourceColumn: ICD_PRCDR_CD15

		annotation SummarizationSetBy = Automatic

	column PRCDR_DT15
		dataType: dateTime
		formatString: Long Date
		lineageTag: fa0d6556-cabc-43ac-afc7-7756f440561a
		summarizeBy: none
		sourceColumn: PRCDR_DT15

		variation Variation
			isDefault
			relationship: 612b370f-1987-459f-a4e8-42cc765bcf1c
			defaultHierarchy: LocalDateTable_ca9ce929-e758-43c8-86c1-e89249888483.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ICD_PRCDR_CD16
		dataType: string
		lineageTag: 77e04805-4171-4d24-ae04-88508031b22d
		summarizeBy: none
		sourceColumn: ICD_PRCDR_CD16

		annotation SummarizationSetBy = Automatic

	column PRCDR_DT16
		dataType: dateTime
		formatString: Long Date
		lineageTag: b55e238f-4aa4-499c-a294-8d1bb90e481c
		summarizeBy: none
		sourceColumn: PRCDR_DT16

		variation Variation
			isDefault
			relationship: 96189263-58d0-4aa1-9769-8f462f7041cf
			defaultHierarchy: LocalDateTable_48db791a-3a81-4586-a3cf-3b24c4671572.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ICD_PRCDR_CD17
		dataType: string
		lineageTag: 032cf9b2-a47f-4093-8252-43d462a168fa
		summarizeBy: none
		sourceColumn: ICD_PRCDR_CD17

		annotation SummarizationSetBy = Automatic

	column PRCDR_DT17
		dataType: dateTime
		formatString: Long Date
		lineageTag: b1c8f72f-2bd1-43ae-b516-4b3917c1b898
		summarizeBy: none
		sourceColumn: PRCDR_DT17

		variation Variation
			isDefault
			relationship: 386d76de-7f24-40b5-a815-44bab5cf82d7
			defaultHierarchy: LocalDateTable_7868bff4-aeb7-405a-866a-1c9c8ad24825.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ICD_PRCDR_CD18
		dataType: string
		lineageTag: f98c4a62-8b27-4219-8ae7-7d6f947df475
		summarizeBy: none
		sourceColumn: ICD_PRCDR_CD18

		annotation SummarizationSetBy = Automatic

	column PRCDR_DT18
		dataType: dateTime
		formatString: Long Date
		lineageTag: 35742346-b3f0-48c7-acda-1fb2547051b9
		summarizeBy: none
		sourceColumn: PRCDR_DT18

		variation Variation
			isDefault
			relationship: 41858f41-2606-4bb7-9ab6-236f28e4ba11
			defaultHierarchy: LocalDateTable_59323a4a-91b4-4389-9d9c-dd7c067db923.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ICD_PRCDR_CD19
		dataType: string
		lineageTag: d7035561-7c0c-46ba-8f7d-98ef440ec484
		summarizeBy: none
		sourceColumn: ICD_PRCDR_CD19

		annotation SummarizationSetBy = Automatic

	column PRCDR_DT19
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1d8da12c-9064-4fb7-9fd0-cd3cf3147e7c
		summarizeBy: none
		sourceColumn: PRCDR_DT19

		variation Variation
			isDefault
			relationship: 100a1340-1833-4280-a00b-a31567333a1d
			defaultHierarchy: LocalDateTable_845cd6cf-7f27-4706-83fe-a9809e11a750.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ICD_PRCDR_CD20
		dataType: string
		lineageTag: 5203a826-7932-48b0-9e0c-bc729c5649a1
		summarizeBy: none
		sourceColumn: ICD_PRCDR_CD20

		annotation SummarizationSetBy = Automatic

	column PRCDR_DT20
		dataType: dateTime
		formatString: Long Date
		lineageTag: a3adf2d9-b588-4657-8a82-c17f0e18ef5a
		summarizeBy: none
		sourceColumn: PRCDR_DT20

		variation Variation
			isDefault
			relationship: 0769bd26-bc5f-41d8-99c3-0cc78701ec14
			defaultHierarchy: LocalDateTable_0091d6f5-2157-40d8-b317-d884ce300a66.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ICD_PRCDR_CD21
		dataType: string
		lineageTag: d54bd9b1-98c6-4d07-b197-880fbfc2d061
		summarizeBy: none
		sourceColumn: ICD_PRCDR_CD21

		annotation SummarizationSetBy = Automatic

	column PRCDR_DT21
		dataType: dateTime
		formatString: Long Date
		lineageTag: bdbfb9e2-aa12-4fdb-9033-f463fdbd3066
		summarizeBy: none
		sourceColumn: PRCDR_DT21

		variation Variation
			isDefault
			relationship: 26f8c597-7a81-45e7-ae8a-28641a1a72e1
			defaultHierarchy: LocalDateTable_6b5e924d-a9d8-45fc-b663-8f663612bf45.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ICD_PRCDR_CD22
		dataType: string
		lineageTag: 57eb8f3b-8df2-4991-aacc-a48ca336820f
		summarizeBy: none
		sourceColumn: ICD_PRCDR_CD22

		annotation SummarizationSetBy = Automatic

	column PRCDR_DT22
		dataType: dateTime
		formatString: Long Date
		lineageTag: 09e62e10-e018-4873-af6d-e55e8844c18d
		summarizeBy: none
		sourceColumn: PRCDR_DT22

		variation Variation
			isDefault
			relationship: da071b10-8442-4483-8151-2103e6872d32
			defaultHierarchy: LocalDateTable_0c96e677-8a33-467b-affd-a2e760d82dd5.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ICD_PRCDR_CD23
		dataType: string
		lineageTag: 18c679fd-9849-46c0-8029-cb0167a2ba3f
		summarizeBy: none
		sourceColumn: ICD_PRCDR_CD23

		annotation SummarizationSetBy = Automatic

	column PRCDR_DT23
		dataType: dateTime
		formatString: Long Date
		lineageTag: 123ef530-d3ab-46a5-9328-e63ebf0bfb0f
		summarizeBy: none
		sourceColumn: PRCDR_DT23

		variation Variation
			isDefault
			relationship: 71ee454d-279e-487b-9347-8683a2c32364
			defaultHierarchy: LocalDateTable_9170e272-e332-41b9-9ac4-59db030bac3b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ICD_PRCDR_CD24
		dataType: string
		lineageTag: eb58c254-a057-4f7b-aced-fcdac0e6fc6f
		summarizeBy: none
		sourceColumn: ICD_PRCDR_CD24

		annotation SummarizationSetBy = Automatic

	column PRCDR_DT24
		dataType: dateTime
		formatString: Long Date
		lineageTag: daff21a1-f056-43f8-8a48-f4df2244e428
		summarizeBy: none
		sourceColumn: PRCDR_DT24

		variation Variation
			isDefault
			relationship: 2a23fac3-e34d-4a88-a158-6d929694e46e
			defaultHierarchy: LocalDateTable_5e0164fa-e3bc-4d38-8fe1-48bc35ffbfd0.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ICD_PRCDR_CD25
		dataType: string
		lineageTag: 37c3d905-6aa9-4eea-93b6-63e8cf98f8e2
		summarizeBy: none
		sourceColumn: ICD_PRCDR_CD25

		annotation SummarizationSetBy = Automatic

	column PRCDR_DT25
		dataType: dateTime
		formatString: Long Date
		lineageTag: c5f9adc1-c6c8-4245-8c30-b0fb1c53584b
		summarizeBy: none
		sourceColumn: PRCDR_DT25

		variation Variation
			isDefault
			relationship: 8af52bce-33e6-45f0-bc2c-4bfb99ac3ce9
			defaultHierarchy: LocalDateTable_f1d5f89c-e80d-412d-a350-16c080fc89a7.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CLM_LINE_NUM
		dataType: int64
		formatString: 0
		lineageTag: 7339db7e-d53a-4c0d-8608-fc78251feb4f
		summarizeBy: sum
		sourceColumn: CLM_LINE_NUM

		annotation SummarizationSetBy = Automatic

	column REV_CNTR
		dataType: int64
		formatString: 0
		lineageTag: 2e8ee27e-1ad7-47bd-b7b4-9e827acfd7bf
		summarizeBy: sum
		sourceColumn: REV_CNTR

		annotation SummarizationSetBy = Automatic

	column HCPCS_CD
		dataType: string
		lineageTag: fa5386e8-8eb8-46d4-85cb-d60289296c45
		summarizeBy: none
		sourceColumn: HCPCS_CD

		annotation SummarizationSetBy = Automatic

	column REV_CNTR_UNIT_CNT
		dataType: int64
		formatString: 0
		lineageTag: 6213605d-d977-4e89-9b9e-9c217a6ec5cb
		summarizeBy: sum
		sourceColumn: REV_CNTR_UNIT_CNT

		annotation SummarizationSetBy = Automatic

	column REV_CNTR_RATE_AMT
		dataType: double
		lineageTag: e604242d-7a0d-474e-a6a2-fdf23f98c67a
		summarizeBy: sum
		sourceColumn: REV_CNTR_RATE_AMT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column REV_CNTR_TOT_CHRG_AMT
		dataType: double
		lineageTag: 9dbb2a3d-41d0-4494-b83e-9202de833edd
		summarizeBy: sum
		sourceColumn: REV_CNTR_TOT_CHRG_AMT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column REV_CNTR_NCVRD_CHRG_AMT
		dataType: double
		lineageTag: 8f602573-3187-4fbd-8636-368ebadd3ffe
		summarizeBy: sum
		sourceColumn: REV_CNTR_NCVRD_CHRG_AMT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column REV_CNTR_DDCTBL_COINSRNC_CD
		dataType: int64
		formatString: 0
		lineageTag: ad737694-15f3-41dc-b4e4-056fe42819ab
		summarizeBy: sum
		sourceColumn: REV_CNTR_DDCTBL_COINSRNC_CD

		annotation SummarizationSetBy = Automatic

	column REV_CNTR_NDC_QTY
		dataType: int64
		formatString: 0
		lineageTag: b2681eaf-34d2-4174-9b20-bc29e643bd31
		summarizeBy: sum
		sourceColumn: REV_CNTR_NDC_QTY

		annotation SummarizationSetBy = Automatic

	column REV_CNTR_NDC_QTY_QLFR_CD
		dataType: string
		lineageTag: 00195310-1a43-4d56-807b-f4be5046e2dc
		summarizeBy: none
		sourceColumn: REV_CNTR_NDC_QTY_QLFR_CD

		annotation SummarizationSetBy = Automatic

	column RNDRNG_PHYSN_UPIN
		dataType: string
		lineageTag: fe08c6ea-a4b1-4a18-8ab9-6b70ad7b3620
		summarizeBy: none
		sourceColumn: RNDRNG_PHYSN_UPIN

		annotation SummarizationSetBy = Automatic

	column RNDRNG_PHYSN_NPI
		dataType: int64
		formatString: 0
		lineageTag: 17d56526-448a-4552-9ff9-eae23fbe9b1e
		summarizeBy: sum
		sourceColumn: RNDRNG_PHYSN_NPI

		annotation SummarizationSetBy = Automatic

	partition snf = m
		mode: import
		source =
				let
				    Source = Folder.Files("C:\Users\dpnsh\Downloads\All FFS Claims"),
				    #"C:\Users\dpnsh\Downloads\All FFS Claims\_snf csv1" = Source{[#"Folder Path"="C:\Users\dpnsh\Downloads\All FFS Claims\",Name="snf.csv"]}[Content],
				    #"Imported CSV" = Csv.Document(#"C:\Users\dpnsh\Downloads\All FFS Claims\_snf csv1",[Delimiter="|", Columns=160, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Imported CSV", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"BENE_ID", Int64.Type}, {"CLM_ID", Int64.Type}, {"NCH_NEAR_LINE_REC_IDENT_CD", type text}, {"NCH_CLM_TYPE_CD", Int64.Type}, {"CLM_FROM_DT", type date}, {"CLM_THRU_DT", type date}, {"NCH_WKLY_PROC_DT", type date}, {"FI_CLM_PROC_DT", type text}, {"CLAIM_QUERY_CODE", Int64.Type}, {"PRVDR_NUM", type text}, {"CLM_FAC_TYPE_CD", Int64.Type}, {"CLM_SRVC_CLSFCTN_TYPE_CD", Int64.Type}, {"CLM_FREQ_CD", Int64.Type}, {"FI_NUM", type text}, {"CLM_MDCR_NON_PMT_RSN_CD", type text}, {"CLM_PMT_AMT", type number}, {"NCH_PRMRY_PYR_CLM_PD_AMT", type number}, {"NCH_PRMRY_PYR_CD", type text}, {"FI_CLM_ACTN_CD", type text}, {"PRVDR_STATE_CD", Int64.Type}, {"ORG_NPI_NUM", Int64.Type}, {"AT_PHYSN_UPIN", type text}, {"AT_PHYSN_NPI", Int64.Type}, {"OP_PHYSN_UPIN", type text}, {"OP_PHYSN_NPI", Int64.Type}, {"OT_PHYSN_UPIN", type text}, {"OT_PHYSN_NPI", type text}, {"CLM_MCO_PD_SW", Int64.Type}, {"PTNT_DSCHRG_STUS_CD", Int64.Type}, {"CLM_PPS_IND_CD", type text}, {"CLM_TOT_CHRG_AMT", type number}, {"CLM_ADMSN_DT", type date}, {"CLM_IP_ADMSN_TYPE_CD", Int64.Type}, {"CLM_SRC_IP_ADMSN_CD", Int64.Type}, {"NCH_PTNT_STATUS_IND_CD", type text}, {"NCH_BENE_IP_DDCTBL_AMT", Int64.Type}, {"NCH_BENE_PTA_COINSRNC_LBLTY_AM", type number}, {"NCH_BENE_BLOOD_DDCTBL_LBLTY_AM", Int64.Type}, {"NCH_IP_NCVRD_CHRG_AMT", type number}, {"NCH_IP_TOT_DDCTN_AMT", type number}, {"CLM_PPS_CPTL_FSP_AMT", Int64.Type}, {"CLM_PPS_CPTL_OUTLIER_AMT", Int64.Type}, {"CLM_PPS_CPTL_DSPRPRTNT_SHR_AMT", Int64.Type}, {"CLM_PPS_CPTL_IME_AMT", Int64.Type}, {"CLM_PPS_CPTL_EXCPTN_AMT", Int64.Type}, {"CLM_PPS_OLD_CPTL_HLD_HRMLS_AMT", Int64.Type}, {"CLM_UTLZTN_DAY_CNT", Int64.Type}, {"BENE_TOT_COINSRNC_DAYS_CNT", Int64.Type}, {"CLM_NON_UTLZTN_DAYS_CNT", Int64.Type}, {"NCH_BLOOD_PNTS_FRNSHD_QTY", Int64.Type}, {"NCH_QLFYD_STAY_FROM_DT", type text}, {"NCH_QLFYD_STAY_THRU_DT", type text}, {"NCH_VRFD_NCVRD_STAY_FROM_DT", type text}, {"NCH_VRFD_NCVRD_STAY_THRU_DT", type text}, {"NCH_ACTV_OR_CVRD_LVL_CARE_THRU", type text}, {"NCH_BENE_MDCR_BNFTS_EXHTD_DT_I", type text}, {"NCH_BENE_DSCHRG_DT", type date}, {"CLM_DRG_CD", Int64.Type}, {"ADMTG_DGNS_CD", type text}, {"PRNCPAL_DGNS_CD", type text}, {"ICD_DGNS_CD1", type text}, {"ICD_DGNS_CD2", type text}, {"ICD_DGNS_CD3", type text}, {"ICD_DGNS_CD4", type text}, {"ICD_DGNS_CD5", type text}, {"ICD_DGNS_CD6", type text}, {"ICD_DGNS_CD7", type text}, {"ICD_DGNS_CD8", type text}, {"ICD_DGNS_CD9", type text}, {"ICD_DGNS_CD10", type text}, {"ICD_DGNS_CD11", type text}, {"ICD_DGNS_CD12", type text}, {"ICD_DGNS_CD13", type text}, {"ICD_DGNS_CD14", type text}, {"ICD_DGNS_CD15", type text}, {"ICD_DGNS_CD16", type text}, {"ICD_DGNS_CD17", type text}, {"ICD_DGNS_CD18", type text}, {"ICD_DGNS_CD19", type text}, {"ICD_DGNS_CD20", type text}, {"ICD_DGNS_CD21", type text}, {"ICD_DGNS_CD22", type text}, {"ICD_DGNS_CD23", type text}, {"ICD_DGNS_CD24", type text}, {"ICD_DGNS_CD25", type text}, {"FST_DGNS_E_CD", type text}, {"ICD_DGNS_E_CD1", type text}, {"ICD_DGNS_E_CD2", type text}, {"ICD_DGNS_E_CD3", type text}, {"ICD_DGNS_E_CD4", type text}, {"ICD_DGNS_E_CD5", type text}, {"ICD_DGNS_E_CD6", type text}, {"ICD_DGNS_E_CD7", type text}, {"ICD_DGNS_E_CD8", type text}, {"ICD_DGNS_E_CD9", type text}, {"ICD_DGNS_E_CD10", type text}, {"ICD_DGNS_E_CD11", type text}, {"ICD_DGNS_E_CD12", type text}, {"ICD_PRCDR_CD1", type text}, {"PRCDR_DT1", type date}, {"ICD_PRCDR_CD2", type text}, {"PRCDR_DT2", type date}, {"ICD_PRCDR_CD3", type text}, {"PRCDR_DT3", type date}, {"ICD_PRCDR_CD4", type text}, {"PRCDR_DT4", type date}, {"ICD_PRCDR_CD5", type text}, {"PRCDR_DT5", type date}, {"ICD_PRCDR_CD6", type text}, {"PRCDR_DT6", type date}, {"ICD_PRCDR_CD7", type text}, {"PRCDR_DT7", type date}, {"ICD_PRCDR_CD8", type text}, {"PRCDR_DT8", type date}, {"ICD_PRCDR_CD9", type text}, {"PRCDR_DT9", type date}, {"ICD_PRCDR_CD10", type text}, {"PRCDR_DT10", type date}, {"ICD_PRCDR_CD11", type text}, {"PRCDR_DT11", type date}, {"ICD_PRCDR_CD12", type text}, {"PRCDR_DT12", type date}, {"ICD_PRCDR_CD13", type text}, {"PRCDR_DT13", type date}, {"ICD_PRCDR_CD14", type text}, {"PRCDR_DT14", type date}, {"ICD_PRCDR_CD15", type text}, {"PRCDR_DT15", type date}, {"ICD_PRCDR_CD16", type text}, {"PRCDR_DT16", type date}, {"ICD_PRCDR_CD17", type text}, {"PRCDR_DT17", type date}, {"ICD_PRCDR_CD18", type text}, {"PRCDR_DT18", type date}, {"ICD_PRCDR_CD19", type text}, {"PRCDR_DT19", type date}, {"ICD_PRCDR_CD20", type text}, {"PRCDR_DT20", type date}, {"ICD_PRCDR_CD21", type text}, {"PRCDR_DT21", type date}, {"ICD_PRCDR_CD22", type text}, {"PRCDR_DT22", type date}, {"ICD_PRCDR_CD23", type text}, {"PRCDR_DT23", type date}, {"ICD_PRCDR_CD24", type text}, {"PRCDR_DT24", type date}, {"ICD_PRCDR_CD25", type text}, {"PRCDR_DT25", type date}, {"CLM_LINE_NUM", Int64.Type}, {"REV_CNTR", Int64.Type}, {"HCPCS_CD", type text}, {"REV_CNTR_UNIT_CNT", Int64.Type}, {"REV_CNTR_RATE_AMT", type number}, {"REV_CNTR_TOT_CHRG_AMT", type number}, {"REV_CNTR_NCVRD_CHRG_AMT", type number}, {"REV_CNTR_DDCTBL_COINSRNC_CD", Int64.Type}, {"REV_CNTR_NDC_QTY", Int64.Type}, {"REV_CNTR_NDC_QTY_QLFR_CD", type text}, {"RNDRNG_PHYSN_UPIN", type text}, {"RNDRNG_PHYSN_NPI", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

